DROP TABLE IF EXISTS VERIZON_TRANSACTIONS;
CREATE TABLE VERIZON_TRANSACTIONS( 
    TRANSACTION_COUNT           INTEGER,
    TRANSACTION_DATE            DATE
);

   -- =========================================================================
   -- LOAD DATA STRAIGHT FROM CSV
   -- =========================================================================
   COPY VERIZON_TRANSACTIONS
   FROM '/LOCAL/KAGGLE/VERIZON/DATA/Transactions.csv'
   USING DELIMITERS E','
   CSV HEADER;
   -- =========================================================================


DROP TABLE IF EXISTS VERIZON_SALES;
CREATE TABLE VERIZON_SALES (
    year                        integer,
    month                       integer,
    sales                       integer
);

   -- =========================================================================
   -- LOAD DATA STRAIGHT FROM CSV
   -- =========================================================================
   COPY VERIZON_SALES
   FROM '/LOCAL/KAGGLE/VERIZON/DATA/Sales.csv'
   USING DELIMITERS E','
   CSV HEADER;
   -- =========================================================================


   -- =========================================================================
select  month, count(year), count(sales), sum(sales) from VERIZON_SALES group by MONTH order by MONTH;
   -- =========================================================================


-- =========================================================================
DROP TABLE IF EXISTS VERIZON_TRANSACTIONS_EXTENDED;
-- =========================================================================
CREATE TABLE VERIZON_TRANSACTIONS_EXTENDED AS (
   SELECT
       TRANSACTION_COUNT,
       TRANSACTION_DATE,
       EXTRACT(ISODOW  FROM TRANSACTION_DATE) AS TRANSACTION_DOW,
       EXTRACT(YEAR    FROM TRANSACTION_DATE) AS TRANSACTION_YEAR,
       EXTRACT(MONTH   FROM TRANSACTION_DATE) AS TRANSACTION_MONTH,
       EXTRACT(QUARTER FROM TRANSACTION_DATE) AS TRANSACTION_QUARTER,
       EXTRACT(WEEK    FROM TRANSACTION_DATE) AS TRANSACTION_WEEK,
       EXTRACT(DOY     FROM TRANSACTION_DATE) AS TRANSACTION_DOY,
       TRANSACTION_DATE - '2013-04-01'::DATE  AS TRANSACTION_DAYNUM,
       AGE(TRANSACTION_DATE, '2013-04-01')    AS TRANSACTION_AGE
   FROM VERIZON_TRANSACTIONS);

COPY (SELECT * FROM VERIZON_TRANSACTIONS_EXTENDED ORDER BY TRANSACTION_DAYNUM) TO '/tmp/VERIZON_TRANSACTIONS_EXTENDED.csv' DELIMITER ','  CSV HEADER;


COPY (
SELECT TRANSACTION_QUARTER, COUNT(TRANSACTION_COUNT), SUM(TRANSACTION_COUNT), AVG(TRANSACTION_COUNT)
    FROM VERIZON_TRANSACTIONS_EXTENDED 
    GROUP BY TRANSACTION_QUARTER 
    ORDER BY TRANSACTION_QUARTER)
TO '/tmp/VERIZON_TRANSACTIONS_BY_QUARTER.csv' DELIMITER ','  CSV HEADER;

COPY (
SELECT TRANSACTION_MONTH, COUNT(TRANSACTION_COUNT), SUM(TRANSACTION_COUNT), AVG(TRANSACTION_COUNT)
    FROM VERIZON_TRANSACTIONS_EXTENDED 
    GROUP BY TRANSACTION_MONTH
    ORDER BY TRANSACTION_MONTH)
TO '/tmp/VERIZON_TRANSACTIONS_BY_MONTH.csv' DELIMITER ','  CSV HEADER;


COPY (
SELECT TRANSACTION_WEEK, COUNT(TRANSACTION_COUNT), SUM(TRANSACTION_COUNT), AVG(TRANSACTION_COUNT)
    FROM VERIZON_TRANSACTIONS_EXTENDED 
    GROUP BY TRANSACTION_WEEK
    ORDER BY TRANSACTION_WEEK)
TO '/tmp/VERIZON_TRANSACTIONS_BY_WEEK.csv' DELIMITER ','  CSV HEADER;

COPY (
SELECT TRANSACTION_DOW, COUNT(TRANSACTION_COUNT), SUM(TRANSACTION_COUNT), AVG(TRANSACTION_COUNT)
    FROM VERIZON_TRANSACTIONS_EXTENDED 
    GROUP BY TRANSACTION_DOW
    ORDER BY TRANSACTION_DOW)
TO '/tmp/VERIZON_TRANSACTIONS_BY_DOW.csv' DELIMITER ','  CSV HEADER;

COPY (
SELECT TRANSACTION_DOY, COUNT(TRANSACTION_COUNT), SUM(TRANSACTION_COUNT), AVG(TRANSACTION_COUNT)
    FROM VERIZON_TRANSACTIONS_EXTENDED 
    GROUP BY TRANSACTION_DOY
    ORDER BY TRANSACTION_DOY)
TO '/tmp/VERIZON_TRANSACTIONS_BY_DOY.csv' DELIMITER ','  CSV HEADER;







DROP TABLE IF EXISTS QUARTERS;
CREATE TABLE QUARTERS AS (
SELECT TRANSACTION_QUARTER, COUNT(TRANSACTION_COUNT), SUM(TRANSACTION_COUNT), AVG(TRANSACTION_COUNT) as QT_AVG
    FROM VERIZON_TRANSACTIONS_EXTENDED 
    GROUP BY TRANSACTION_QUARTER 
    ORDER BY TRANSACTION_QUARTER);

DROP TABLE IF EXISTS MONTHS;
CREATE TABLE MONTHS AS (
SELECT TRANSACTION_MONTH, COUNT(TRANSACTION_COUNT), SUM(TRANSACTION_COUNT), AVG(TRANSACTION_COUNT) as MONTH_AVG
    FROM VERIZON_TRANSACTIONS_EXTENDED 
    GROUP BY TRANSACTION_MONTH
    ORDER BY TRANSACTION_MONTH);

DROP TABLE IF EXISTS WEEKS;
CREATE TABLE WEEKS AS (
SELECT TRANSACTION_WEEK, COUNT(TRANSACTION_COUNT), SUM(TRANSACTION_COUNT), AVG(TRANSACTION_COUNT) as WEEK_AVG
    FROM VERIZON_TRANSACTIONS_EXTENDED 
    GROUP BY TRANSACTION_WEEK
    ORDER BY TRANSACTION_WEEK);

DROP TABLE IF EXISTS DOWS;
CREATE TABLE DOWS AS (
SELECT TRANSACTION_DOW, COUNT(TRANSACTION_COUNT), SUM(TRANSACTION_COUNT), AVG(TRANSACTION_COUNT) as DOW_AVG
    FROM VERIZON_TRANSACTIONS_EXTENDED 
    GROUP BY TRANSACTION_DOW
    ORDER BY TRANSACTION_DOW);

DROP TABLE IF EXISTS DOYS;
CREATE TABLE DOYS AS (
SELECT TRANSACTION_DOY, COUNT(TRANSACTION_COUNT), SUM(TRANSACTION_COUNT), AVG(TRANSACTION_COUNT) AS DOY_AVG
    FROM VERIZON_TRANSACTIONS_EXTENDED 
    GROUP BY TRANSACTION_DOY
    ORDER BY TRANSACTION_DOY);



DROP TABLE IF EXISTS VERIZON_TRANSACTIONS_EXTENDED_JOINED;
CREATE TABLE VERIZON_TRANSACTIONS_EXTENDED_JOINED AS (
   SELECT
       T0.*,
       DOY_AVG,
       DOW_AVG,
       WEEK_AVG,
       MONTH_AVG,
       QT_AVG
   FROM VERIZON_TRANSACTIONS_EXTENDED T0
        INNER JOIN DOYS T1 ON(T0.TRANSACTION_DOY=T1.TRANSACTION_DOY)
        INNER JOIN DOWS T2 ON(T0.TRANSACTION_DOW=T2.TRANSACTION_DOW)
        INNER JOIN WEEKS T3 ON(T0.TRANSACTION_WEEK=T3.TRANSACTION_WEEK)
        INNER JOIN MONTHS T4 ON(T0.TRANSACTION_MONTH=T4.TRANSACTION_MONTH)
        INNER JOIN QUARTERS T5 ON(T0.TRANSACTION_QUARTER=T5.TRANSACTION_QUARTER)
    );

COPY (SELECT * FROM VERIZON_TRANSACTIONS_EXTENDED_JOINED ORDER BY TRANSACTION_DAYNUM) TO '/tmp/VERIZON_TRANSACTIONS_EXTENDED_JOINED.csv' DELIMITER ','  CSV HEADER;

