;; ****************************************************************************************************
;;                             FROM HPS SERIES TO TEXT - REPORT
;; ****************************************************************************************************
;; function decodes a steno time series looking for the presence of HPS states which are then 
;; mapped into a text string by using a shared knowledge alphabet-code mapping (shown below). 
;; the function reads the HPS time series, which is required to be of 3601 samples, as produced,
;; by the simulator and then generates the corresponding HPS state sequence. These HPS states
;; are of variable length and their mean value represents a representative value coding for a letter.
;; ****************************************************************************************************


;; ********************************************************************************************
;; ********************************************************************************************
;; THIS MODULE IS PART OF AN IMPLEMENTATION OF AN ONLINE HPS TRANSFORM.  THE HPS TRANSFORM WAS 
;; DESCRIBED IN THE PAPER ENTITLED: 
;; 			    THE HPS TRANSFORM AND ITS APPLICATIONS
;;                          www3.webng.com/nelsonmanohar/research/
;;
;; 	          THIS CODE WAS WRITTEN AND ITS COPYRIGHTED (2007) BY 
;; 			    DR. NELSON R. MANOHAR ALERS
;; 			      nelsonmanohar@yahoo.com
;; 			           AUGUST 2007
;;
;; THIS CODE IS NOT IN THE PUBLIC DOMAIN. THIS CODE IS NOT INTENDED FOR DISTRIBUTION. PLEASE DO
;; NOT MODIFY THIS CODE. PLEASE INFORM THE AUTHOR OF ANY UNINTENDED OR UNAUTHORIZED DISTRIBUTION 
;; AND/OR ACCESS TO THIS CODE.
;; ********************************************************************************************



;; ################################################################################
;; #  		From The HPS Transform and Its Applications
;; #                          By Dr. Nelson R. Manohar
;; # this script is used to generate figures for the output generated by
;; # the HPS transform. These figures are integrated into a html report 
;; # which conveniently summarizes the output obtained after the application
;; # of the HPS transform to an input series. Reports can be customized
;; # according to application and domain, and can be customized to select
;; # the level of detail to present.
;; #
;; # initialization, it is assumed that the HPS transform was previously applied 
;; # as a result, a directory HPS_DATA must exist on the selected drive C:\
;; ################################################################################


(defmacro HPS_STENO_DECODER_PLOT () "
################################################################################
# INITIALIZATION
################################################################################
reset
set palette color
cd \"~A\" 
	# E:/HPS_DATA
################################################################################

################################################################################
# RESULTANT HPS APPROXIMATION SIGNAL SET
################################################################################
reset
set format y \"%4.0f\"
set title 'RESULTANT HPS APPROXIMATION AND AUTOMATED DECODING'
set terminal png giant butt size 1200,800 enhanced
set grid
set output \"~A\"
	# name of figure file HPS_OUTPUTS/HPS-STENO-TIMEPLOTS-AND-HISTOGRAMS.PNG
set multiplot
        ################################################################################
	set size 1.0, 0.20
	set origin 0, 0.75
	set tmargin 0
	set bmargin 0
	set title 'HPS INPUT SIGNAL (STENOGRAPHIC MESSAGE EMBEDDED WITHIN NOISE BACKGROUND)'
	set xlabel ''
	set ylabel 'HPS input signal y(i)'
	plot  \"HPS_INPUTS/HPS_INPUT_SERIES.DAT\"    using 1:2   title 'HPS input signal (i)' with impulses lw 1
        ################################################################################
	set title 'RESULTANT HPS APPROXIMATION AND AUTOMATED DECODING'
	set bmargin 0
	set size 1.0, 0.35
	set origin 0, 0.30
	set yrange [-15:15]
	set xlabel ''
	set ylabel 'HPS approximation (i)'
	~A
		# seg-labels   
	set ytics autofreq (\"---B\" -13, \"--G-\" -12, \"-Y--\" -11, \"A---\" -10, \"---K\" -9, \"--E-\" -8, \"-V--\" -7, \"H---\" -6, \"----\" -5, \"--R-\" -4, \"-I--\" -3, \"X---\" -2, \"---W\" -1, \"--N-\" 0, \"-L--\" 1, \"P---\" 2, \"---T\" 3, \"--Q-\" 4,\"-D--\" 5, \"S---\" 6, \"---O\" 7, \"--J-\" 8, \"-M--\" 9, \"C---\" 10, \"---F\" 11, \"--Z-\" 12, \"-U--\" 13 )
	plot  \"HPS_OUTPUTS/HPS_APPROXIMATION.DAT\"  using 1:2   title 'HPS forecast (i)' with impulses lw 1
	set autoscale y
	reset
        ################################################################################
	########################################################################
	set grid
	set format y \"%4.0f\"
	set title 'HISTOGRAM OF HPS INPUT SIGNAL'
	set size 0.50, 0.20
        set origin 0.00, 0.00
	set tmargin 0
	set ylabel 'frequency'
	set xlabel 'HPS input signal range'
	plot \"HPS_OUTPUTS/HPS_HISTOGRAM_INPUT_SERIES.DAT\" using 1:2 title 'HPS input signal' with steps
       	################################################################################
	set title 'HISTOGRAM OF HPS APPROXIMATION'
	set size 0.50, 0.20
        set origin 0.50, 0.00
	set xrange [-15:15]
	set ylabel 'frequency'
	set xlabel 'HPS approximation range'

	set xtics autofreq (\"B\"  -13,  \"G\"  -12,  \"Y\" -11,  \"A\" -10,  \"K\" -9,  \"E\" -8,  \"V\" -7,  \"H\" -6,  \"J\" -5,  \"R\" -4,  \"I\" -3,  \"X\" -2,  \"W\" -1,  \"N\" 0,  \"L\" 1, \"P\" 2, \"T\" 3, \"Q\" 4, \"D\" 5, \"S\" 6, \"O\" 7, \"-\" 8, \"M\" 9, \"C\" 10, \"F\" 11, \"Z\" 12, \"U\" 13 )
	plot \"HPS_OUTPUTS/HPS_HISTOGRAM_HPS_APPROXIMATION.DAT\" using 1:2 title 'HPS approximation' with steps
       	################################################################################
	unset multiplot
	########################################################################
################################################################################
")



;; ***********************************************************************************************
;; this function creates gnuplot labels for the steno decoded values
;; ***********************************************************************************************
(defun HPS_STENO_make_seglabels_for ( segtable )
	(with-output-to-string ( *HPS_internal_buffer* ) 
	  	(setf iter 0)
		(dolist (segelem segtable 'seglabels)
		  	(setf plot_x (first  segelem))
			(incf plot_x 2)
		  	(setf plot_y (fourth segelem))
			(if (< plot_y 0) (decf plot_y 1) (incf plot_y 1))
		  	(setf seg_code (STENO_getmapletter (fourth segelem)))
		  	(format *HPS_internal_buffer* "~%set label \"~A\" at ~6,0F, ~6,0F front font \"Times, 7\"" seg_code plot_x plot_y)
			(incf iter))
		(setf seglabels (get-output-stream-string *HPS_internal_buffer*)))
	(return-from HPS_STENO_make_seglabels_for seglabels ))
;; ***********************************************************************************************


;; ***********************************************************************************************
;; ***********************************************************************************************
(defun HPS_STENO_decoder_gnuplot ( segtable basedir filename figfilename ) 
  	(setf seglabels (HPS_STENO_make_seglabels_for segtable ))
	(with-open-file (report-stream filename :direction :output :if-exists :supersede :if-does-not-exist :create)
  		(format report-stream (HPS_STENO_DECODER_PLOT) basedir figfilename seglabels )))
;; ***********************************************************************************************


