;; ****************************************************************************************************
;;                             FROM HPS SERIES TO TEXT - REPORT
;; ****************************************************************************************************
;; function decodes a steno time series looking for the presence of HPS states which are then 
;; mapped into a text string by using a shared knowledge alphabet-code mapping (shown below). 
;; the function reads the HPS time series, which is required to be of 3601 samples, as produced,
;; by the simulator and then generates the corresponding HPS state sequence. These HPS states
;; are of variable length and their mean value represents a representative value coding for a letter.
;; ****************************************************************************************************


;; ********************************************************************************************
;; ********************************************************************************************
;; THIS MODULE IS PART OF AN IMPLEMENTATION OF AN ONLINE HPS TRANSFORM.  THE HPS TRANSFORM WAS 
;; DESCRIBED IN THE PAPER ENTITLED: 
;; 			    THE HPS TRANSFORM AND ITS APPLICATIONS
;;                          www3.webng.com/nelsonmanohar/research/
;;
;; 	          THIS CODE WAS WRITTEN AND ITS COPYRIGHTED (2007) BY 
;; 			    DR. NELSON R. MANOHAR ALERS
;; 			      nelsonmanohar@yahoo.com
;; 			           AUGUST 2007
;;
;; THIS CODE IS NOT IN THE PUBLIC DOMAIN. THIS CODE IS NOT INTENDED FOR DISTRIBUTION. PLEASE DO
;; NOT MODIFY THIS CODE. PLEASE INFORM THE AUTHOR OF ANY UNINTENDED OR UNAUTHORIZED DISTRIBUTION 
;; AND/OR ACCESS TO THIS CODE.
;; ********************************************************************************************



;; ################################################################################
;; #  		From The HPS Transform and Its Applications
;; #                          By Dr. Nelson R. Manohar
;; # this script is used to generate figures for the output generated by
;; # the HPS transform. These figures are integrated into a html report 
;; # which conveniently summarizes the output obtained after the application
;; # of the HPS transform to an input series. Reports can be customized
;; # according to application and domain, and can be customized to select
;; # the level of detail to present.
;; #
;; # initialization, it is assumed that the HPS transform was previously applied 
;; # as a result, a directory HPS_DATA must exist on the selected drive C:\
;; ################################################################################


(defmacro HPS_STENO_HTML_REPORT () "
<HTML> <HEAD> <TITLE>HPS STENO DECODER REPORT</TITLE> <STYLE>
<!--
@font-face {font-family:Verdana; panose-1:2 11 6 4 3 5 4 4 2 4;}
@font-face {font-family:Garamond; panose-1:2 2 4 4 3 3 1 1 8 3;}
p.MsoNormal, li.MsoNormal, div.MsoNormal {margin:0in; margin-bottom:.0001pt; font-size:9.0pt; font-family:Verdana;}
@page Section0 {size:8.5in 11.0in; margin:0.5in 0.5in 0.5in 0.5in; font-size:9.0pt; font-family:Verdana;}
div.Section0 {page:Section0;}
-->
</STYLE> </HEAD> <BODY LANG=EN-US> 
<DIV CLASS=MSONORMAL ALIGN=center>
<H2> HPS STENOGRAPHIC DECODER DRAFT REPORT </H2>
<P> <STRONG> 
(c) 2007 <A HREF=http://www3.webng.com/nelsonmanohar/research.htm> The HPS Transform <BR> by Nelson R. Manohar, Ph.D.  </A> 
<BR> nelsonmanohar@yahoo.com </STRONG> </P>

<DIV ALIGN=JUSTIFY>	
<P> 	This report contains the results of the HPS decoding of the input series you provided performed under the decoding 
	parameters that were supplied. The resulting message is presented first followed by timeplots and histograms for 
	the input signal and its resultant HPS approximation made available for detailed examination.  Information about 
	the HPS transform (and the resultant HPS approximation) is provided at the end of this report. </P>
</DIV>


~A


<BR> <BR> <BR> <BR>
<H3>ABOUT THE HPS TRANSFORM </H3>
<DIV ALIGN=JUSTIFY>	
<P> 	The <STRONG>HPS Transform</STRONG> allows the unearthing of a \"form of\" timescale information from a signal.  Although 
	the <STRONG>HPS Transform</STRONG> is particularly suited for adaptive process control, the results have vast implications 
	to other fields.  In particular, important applications of the <STRONG>HPS Transform</STRONG> relate to feature extraction 
	and data-mining.  For example, the <STRONG>HPS Transform</STRONG> is particularly useful in distributed, loosely-coupled, 
	adaptive process control applications where a client <I>C</I> performs monitoring of a local resource <I>R</I> with sampling 
	effort <I>&#9553;‹y(i)›&#9553;</I> but now needs to report to a remote server <I>S</I> <I>only</I> only on certain changes 
	over a state memory <I>‹&#960;(k)›,</I> thus exhibiting a reduction property <I>&#9553;k&#9553; significantly less than 
	&#9553;i&#9553;</I>.  The <STRONG>HPS Transform</STRONG> exhibits most desirable qualities on implementation ease, algorithmic 
	complexity (i.e., O(N) - linear time worst time computational time), computational stability (i.e., stable operation region), 
	signal compressibility, (e.g., large ratio, controllable error/compression ratio), decision-making robustness (e.g., 
	robustness to outliers, timescale independent, robustness to lack of information about the input signal's distribution, 
	etc.) information loss, and error behavior (i.e., bounded error and known confidence levels).  The HPS transform achieves 
	this by trading off a small but specifiable delay, this being measured in terms of samples (and not time).  
</P>
	<SPAN> <A HREF=\"HPS_REPORT_TRANSFORM.HTM\" TARGET=_BLANK > CLICK HERE TO ACCESS THE RESULTANT HPS APPROXIMATION </A> </SPAN>
<P> 	This report is automatically generated by the HPS stenographic decoder. Access to this stenographic report is provided only to 
	illustrate the discrimination power achievable by the HPS transform.  No permit to use is granted without authorization from the 
	author. Due to malfeasance, the stenographic application can not be made available for anonymous use. Only qualified reviewers 
	and academics may request access to the application by e-mailing your specific request to the author to the e-mail address given.
</P>
</DIV>

</BODY> </HTML> 
")

(defmacro HPS_STENO_FIG_ENTRY () "
<DIV ALIGN=CENTER>	<TABLE ALIGN=CENTER BGCOLOR=#E6F2FF > <TR> <TD ALIGN=CENTER> 
<IFRAME SRC=\"HPS_OUTPUTS/HPS-STENO-TIMEPLOTS-AND-HISTOGRAMS_~D_~D.PNG\" WIDTH=1200 HEIGHT=800 MARGINWIDTH=0 MARGINHEIGHT=0 FRAMEBORDER=YES SCROLLING=NO> </IFRAME> 
</TD> </TR> <TH> \"PLOTS FOR DECODING AT ~D, ~D\" </TH> </TABLE> </DIV>
")



