(setf HPS_COMPILE_AND_LOAD_IS_ON t)

;; ********************************************************************************************
;; THIS IS AN IMPLEMENTATION OF AN ONLINE HPS TRANSFORM.  THE HPS TRANSFORM WAS DESCRIBED IN:
;; 			    THE HPS TRANSFORM AND ITS APPLICATIONS
;;                          WWW3.WEBNG.COM/NELSONMANOHAR/RESEARCH/
;;
;;              THIS PARTICULAR IMPLEMENTATION HAS O(m' N) TIME COMPLEXITY 
;;     THE OPTIMAL IMPLEMENTATION HAS O(c N)) TIME COMPLEXITY AND O(c N) SPACE COMPLEXITY 
;;         (when state tracking information used primarely for debugging is removed, 
;;               this can be achieved by setting the hps_fulloutputmode flag). 
;;
;; 	                THIS CODE WAS WRITTEN AND ITS COPYRIGHTED (2007) BY 
;; 			       DR. NELSON R. MANOHAR ALERS
;; 			         nelsonmanohar@yahoo.com
;; 			                 AUGUST 2007
;; 			               SEPTEMBER 2007
;;
;;                    NO WARRANTIES EXPRESS OR IMPLIED ARE PROVIDED. ETC. 
;;                       PLACEHOLDER FOR ACTUAL DISCLOSURE STATEMENTS.
;;
;;                          THIS CODE IS NOT IN THE PUBLIC DOMAIN. 
;;                        THIS CODE IS NOT INTENDED FOR DISTRIBUTION. 
;;           PLEASE DO NOT MODIFY THIS SOFTWARE NOT REVERSE ENGINEER THIS SOFTWARE. 
;;     PLEASE INFORM THE AUTHOR OF ANY UNINTENDED OR UNAUTHORIZED DISTRIBUTION OF THIS CODE.
;;
;; ACCESS TO THE HPS TRANSFORM FOR NON-COMMERCIAL AND EDUCATIONAL PURPOSES IS PROVIDED THROUGH
;; EXECUTABLE/COMPILED DERIVATIVE VERSIONS OF THIS CODE PROVIDED FROM THE AUTHOR TO QUALIFIED
;; ACADEMICS AND REVIEWERS. 
;;
;; RUN-TIME VERSIONS OF THIS SOFTWARE ARE AVAILABLE FOR DOWNLOAD BY QUALIFIED PARTIES AT:
;;                      WWW3.WEBNG.COM/NELSONMANOHAR/RESEARCH/HPS
;;
;; OTHERS DESIRING TO USE THE HPS TRANSFORM FOR OTHER PURPOSES OR THOSE NEEDING MORE INCLUSIVE 
;; ACCESS/VERSIONS OF THIS CODE, PLEASE BE SO KIND TO CONTACT THE AUTHOR AT:
;; 			         NELSONMANOHAR@YAHOO.COM
;; ********************************************************************************************







