(proclaim '(optimize (speed 1) (safety 1) (space 3) (debug 0)))

;; *******************************************************************************************************
;; GLOBAL VARIABLES USED WITHIN AND USED FOR DEBUGGING AND NAME COMPLETION
;; *******************************************************************************************************
	(defvar		HPS_COMPILE_AND_LOAD_IS_ON 					nil	"description"   )
	(defvar		*ATS_SEG*							nil	"description"	)
	(defvar		*ATS_SEG_ORIG_VAL*						nil	"description"	)
	(defvar		*ATS_SEG_TIME_INDEX*						nil	"description"	)
	(defvar		*ATS_SEG_TUPLE*							nil	"description"	)
	(defvar		*DIFF_DUR*							nil	"description"	)
	(defvar		*DIFF_IDX*							nil	"description"	)
	(defvar		*DIFF_VAL*							nil	"description"	)
	(defvar		*DNA_OUTPUT_PATH*						nil	"description"	)
	(defvar		*GNU_GET_HTTP_FILE*						nil	"description"	)
	(defvar		*GNU_GNUPLOT_PATH*						nil	"description"	)
	(defvar		*GNU_OUTPUT_PATH*						nil	"description"	)
	(defvar		*HPS_1DNA_ACTUAL_INPUT_BASES*					nil	"description"	)
	(defvar		*HPS_1DNA_ACTUAL_INPUT_DATASET*					nil	"description"	)
	(defvar		*HPS_1DNA_ALIGNMENT_INDEX_WITHIN_TESTSEQ*			nil	"description"	)
	(defvar		*HPS_1DNA_BASES_ONLY*						nil	"description"	)
	(defvar		*HPS_1DNA_BASES_XY_TIMESERIES*					nil	"description"	)
	(defvar		*HPS_1DNA_ENCODED_SEQUENCE_FILE*				nil	"description"	)
	(defvar		*HPS_1DNA_ENDPOINT_SIGNATURE_END*				nil	"description"	)
	(defvar		*HPS_1DNA_ENDPOINT_SIGNATURE_START*				nil	"description"	)
	(defvar		*HPS_1DNA_FILEREADER_BASES_SEQUENCE*				nil	"description"	)
	(defvar		*HPS_1DNA_FILLER_BASES_LEN*					nil	"description"	)
	(defvar		*HPS_1DNA_FULL_INPUT_SEQUENCE_XYZ*				nil	"description"	)
	(defvar		*HPS_1DNA_INPUT_BASES_SIGNATURE*				nil	"description"	)
	(defvar		*HPS_1DNA_INPUT_BASES_TEMP*					nil	"description"	)
	(defvar		*HPS_1DNA_INPUT_BASES_TESTSUBSEQ*				nil	"description"	)
	(defvar		*HPS_1DNA_INPUT_TIMESERIES*					nil	"description"	)
	(defvar		*HPS_1DNA_INPUT_TIMESERIES_CODED*				nil	"description"	)
	(defvar		*HPS_1DNA_MATCHING_BASES_COMPARISON_TEMP*			nil	"description"	)
	(defvar		*HPS_1DNA_MATCHING_CODED_COMPARISON_PRETTY_PRINT*		nil	"description"	)
	(defvar		*HPS_1DNA_MATCHING_CODED_COMPARISON_PRETTY_PRINT_XYZ*		nil	"description"	)
	(defvar		*HPS_1DNA_MATCHING_CODED_COMPARISON_TEMP*			nil	"description"	)
	(defvar		*HPS_1DNA_MUTATED_BASES*					nil	"description"	)
	(defvar		*HPS_1DNA_MUTATED_SEQUENCE*					nil	"description"	)
	(defvar		*HPS_1DNA_SEQUENCE_FILENAME*					nil	"description"	)
	(defvar		*HPS_1DNA_SERIES_STABILIZER_FILLER*				nil	"description"	)
	(defvar		*HPS_1DNA_SERIES_TITLE*						nil	"description"	)
	(defvar		*HPS_1DNA_SIGNATURE_BASES*					nil	"description"	)
	(defvar		*HPS_1DNA_SIGNATURE_BASES_LEN*					nil	"description"	)
	(defvar		*HPS_1DNA_SIGNATURE_CODED*					nil	"description"	)
	(defvar		*HPS_1DNA_SIGNATURE_INPUT_DATASET_XYZ*				nil	"description"	)
	(defvar		*HPS_1DNA_TESTSEQUENCE_BASES*					nil	"description"	)
	(defvar		*HPS_1DNA_TESTSEQUENCE_CODED*					nil	"description"	)
	(defvar		*HPS_1DNA_TESTSEQUENCE_INPUT_DATASET_XYZ*			nil	"description"	)
	(defvar		*HPS_4DNA*							nil	"description"   )
	(defvar		*HPS_3DNA*							nil	"description"	)
	(defvar		*HPS_2DNA*							nil	"description"   )
	(defvar		*HPS_3DNA_ALL_SIG2SUBSEQ_PAIRINGS*				nil	"description"	)
	(defvar		*HPS_3DNA_ALLPAIRS_SEARCH_RESULT*				nil	"description"	)
	(defvar		*HPS_3DNA_ALLPAIRS_WITHIN_WINDOW*				nil	"description"	)
	(defvar		*HPS_3DNA_BASES_CODED*						nil	"description"	)
	(defvar		*HPS_3DNA_DIFF_DUR*						nil	"description"	)
	(defvar		*HPS_3DNA_DIFF_IDX*						nil	"description"	)
	(defvar		*HPS_3DNA_DIFF_VAL*						nil	"description"	)
	(defvar		*HPS_3DNA_ENCODED_SEQ_FILE*					nil	"description"	)
	(defvar		*HPS_3DNA_ENDPOINT_SIGNATURE_END*				nil	"description"	)
	(defvar		*HPS_3DNA_ENDPOINT_SIGNATURE_START*				nil	"description"	)
	(defvar		*HPS_3DNA_ENDPOINT_TESTSEQUENCE_END*				nil	"description"	)
	(defvar		*HPS_3DNA_ENDPOINT_TESTSEQUENCE_START*				nil	"description"	)
	(defvar		*HPS_3DNA_ENDPOINTS_SIGNATURE*					nil	"description"	)
	(defvar		*HPS_3DNA_ENDPOINTS_TESTSEQUENCE*				nil	"description"	)
	(defvar		*HPS_3DNA_HASH_LOOKUP_KEY*					nil	"description"	)
	(defvar		*HPS_3DNA_HASH_LOOKUP_VAL*					nil	"description"	)
	(defvar		*HPS_3DNA_INPUTFILE*						nil	"description"	)
	(defvar		*HPS_3DNA_SEGTABLE_FILE*					nil	"description"	)
	(defvar		*HPS_3DNA_SEGTABLE_HASHTABLE*					nil	"description"	)
	(defvar		*HPS_3DNA_SIGNATURE_BASES*					nil	"description"	)
	(defvar		*HPS_3DNA_SIGNATURE_CODED*					nil	"description"	)
	(defvar		*HPS_3DNA_SIGNATURE_DATASET*					nil	"description"	)
	(defvar		*HPS_3DNA_SIGNATURE_SEGTABLE*					nil	"description"	)
	(defvar		*HPS_3DNA_SIGNATURE_SIZE*					nil	"description"	)
	(defvar		*HPS_3DNA_STENO_SEGTABLE*					nil	"description"	)
	(defvar		*HPS_3DNA_TESTSEQUENCE_BASES*					nil	"description"	)
	(defvar		*HPS_3DNA_TESTSEQUENCE_CODED*					nil	"description"	)
	(defvar		*HPS_3DNA_TESTSEQUENCE_DATASET*					nil	"description"	)
	(defvar		*HPS_3DNA_TESTSEQUENCE_SIZE*					nil	"description"	)
	(defvar		*HPS_ACCESS_WWW_SEQS*						nil	"description"	)
	(defvar		*HPS_ALIGNMENT_INDEXES_BY_TIME*					nil	"description"	)
	(defvar		*HPS_ALPHA*							nil	"description"	)
	(defvar		*HPS_APPROXIMATION_SUBSEQ*					nil	"description"	)
	(defvar		*HPS_ATS_DM_MSEERR_CONSTRAINT*					nil	"description"	)
	(defvar		*HPS_ATS_DM_STATIONARY_FAILED*					nil	"description"	)
	(defvar		*HPS_ATS_DM_STATIONARY_UPHELD*					nil	"description"	)
	(defvar		*HPS_ATS_FINE_TRACKING*						nil	"description"	)
	(defvar		*HPS_ATS_LACKOF_CLIPPING_MARK*					nil	"description"	)
	(defvar		*HPS_ATS_MSEERR_BUILDUP_DELAY*					nil	"description"	)
	(defvar		*HPS_ATS_MSEERR_RELAXATION_FC*					nil	"description"	)
	(defvar		*HPS_ATS_PRINTABLE_SEGMENT_DURATION*				nil	"description"	)
	(defvar		*HPS_ATS_SEGMENT*						nil	"description"	)
	(defvar		*HPS_ATS_SEGMENT_START_INDEX*					nil	"description"	)
	(defvar		*HPS_ATS_SEGMENT_TRACKING*					nil	"description"	)
	(defvar		*HPS_ATS_SEGMENTS_STACK*					nil	"description"	)
	(defvar		*HPS_ATS_TRIVIAL_SEGMENT_DURATION*				nil	"description"	)
	(defvar		*HPS_AUTODIAG_BASICALLY_GOOD_ITER*				nil	"description"	)
	(defvar		*HPS_AVERAGE_SEGMENT_DURATION*					nil	"description"	)
	(defvar		*HPS_BAD_FRATIO*						nil	"description"	)
	(defvar		*HPS_BAD_P_INDEX_VALUE*						nil	"description"	)
	(defvar		*HPS_BAD_REL_ERROR*						nil	"description"	)
	(defvar		*HPS_BAD_Z_ERROR*						nil	"description"	)
	(defvar		*HPS_BAD_ZVALUE*						nil	"description"	)
	(defvar		*HPS_BASE_DIRECTORY*						nil	"description"	)
	(defvar		*HPS_BASE_PATH*							nil	"description"	)
	(defvar		*HPS_CLIPPED_SAMPLE*						nil	"description"	)
	(defvar		*HPS_CLIPPING*							nil	"description"	)
	(defvar		*HPS_COMPRESSIBILITY*						nil	"description"	)
	(defvar		*HPS_COMPUTATION_STATE*						nil	"description"	)
	(defvar		*HPS_CONDITIONED_TS*						nil	"description"	)
	(defvar		*HPS_CONFINTV_HIGH*						nil	"description"	)
	(defvar		*HPS_CONFINTV_LOW*						nil	"description"	)
	(defvar		*HPS_CURRENT_INTERVALS*						nil	"description"	)
	(defvar		*HPS_CURRENT_INTERVALS_STACK*					nil	"description"	)
	(defvar		*HPS_DATASET*							nil	"description"	)
	(defvar		*HPS_DF_HEADERS*						nil	"description"	)
	(defvar		*HPS_DISTORTION*						nil	"description"	)
	(defvar		*HPS_DNA_ALL_PATTERNS_FOUND*					nil	"description"	)
	(defvar		*HPS_DNA_ALLPAIRS_FORX*						nil	"description"	)
	(defvar		*HPS_DNA_ALLPAIRS_TUPLE*					nil	"description"	)
	(defvar		*HPS_DNA_APPROX_TUPLESET*					nil	"description"	)
	(defvar		*HPS_DNA_BASEDIR*						nil	"description"	)
	(defvar		*HPS_DNA_BEST_MATCHING_PATTERNS*				nil	"description"	)
	(defvar		*HPS_DNA_BEST_MATCHING_PATTERNS_SORTED_BY_RANK*			nil	"description"	)
	(defvar		*HPS_DNA_BEST_MATCHING_PATTERNS_SORTED_BY_TIME*			nil	"description"	)
	(defvar		*HPS_DNA_BESTMATCHES*						nil	"description"	)
	(defvar		*HPS_DNA_BESTMATCHES_ORDERED_BY_RANK*				nil	"description"	)
	(defvar		*HPS_DNA_BESTMATCHES_ORDERED_BY_TIME*				nil	"description"	)
	(defvar		*HPS_DNA_DEBUG*							nil	"description"	)
	(defvar		*HPS_DNA_DETAILED_FILENAME*					nil	"description"	)
	(defvar		*HPS_DNA_DETAILED_FILENAME_PLOT_1*				nil	"description"	)
	(defvar		*HPS_DNA_DETAILED_FILENAME_PLOT_2*				nil	"description"	)
	(defvar		*HPS_DNA_DETAILED_REPORT_FILENAME*				nil	"description"	)
	(defvar		*HPS_DNA_DISTANCE_METRICS_TUPLE*				nil	"description"	)
	(defvar		*HPS_DNA_DISTANCE_METRICS_TUPLE_PART_B*				nil	"description"	)
	(defvar		*HPS_DNA_DOT_PRODUCT_TIMESERIES*				nil	"description"	)
	(defvar		*HPS_DNA_ENDPOINT_SIGNATURE_END*				nil	"description"	)
	(defvar		*HPS_DNA_ENDPOINT_SIGNATURE_START*				nil	"description"	)
	(defvar		*HPS_DNA_ENDPOINT_SIGNATURE_STARTP*				nil	"description"	)
	(defvar		*HPS_DNA_ENDPOINT_TESTSEQUENCE_END*				nil	"description"	)
	(defvar		*HPS_DNA_ENDPOINT_TESTSEQUENCE_START*				nil	"description"	)
	(defvar		*HPS_DNA_ENDPOINT_TESTSEQUENCE_STARTP*				nil	"description"	)
	(defvar		*HPS_DNA_ENDPOINTS_SIGNATURE*					nil	"description"	)
	(defvar		*HPS_DNA_ENDPOINTS_TESTSEQUENCE*				nil	"description"	)
	(defvar		*HPS_DNA_ENTREZ_SEQUENCE_HTML_FILE*				nil	"description"	)
	(defvar		*HPS_DNA_EPSILON*						nil	"description"	)
	(defvar		*HPS_DNA_FILENAME*						nil	"description"	)
	(defvar		*HPS_DNA_FITNESS_METRICS_TUPLE*					nil	"description"	)
	(defvar		*HPS_DNA_FITNESS_SCORE*						nil	"description"	)
	(defvar		*HPS_DNA_FORMAT_STRING*						nil	"description"	)
	(defvar		*HPS_DNA_GENBANK_DNA_FILE_CONTENTS*				nil	"description"	)
	(defvar		*HPS_DNA_GENBANK_SEQUENCE*					nil	"description"	)
	(defvar		*HPS_DNA_GENBANK_SEQUENCE_TEMP*					nil	"description"	)
	(defvar		*HPS_DNA_HIGHCOST_FLAG0*					nil	"description"	)
	(defvar		*HPS_DNA_HIGHCOST_FLAG1*					nil	"description"	)
	(defvar		*HPS_DNA_HISTOGRAM_FILENAME*					nil	"description"	)
	(defvar		*HPS_DNA_HTML_MAIN_FOOTER*					nil	"description"	)
	(defvar		*HPS_DNA_HTML_MAIN_HEADER*					nil	"description"	)
	(defvar		*HPS_DNA_HTML_MAIN_HEADER_TOPLEVEL*				nil	"description"	)
	(defvar		*HPS_DNA_HTML_SEQUENCE_FILENAME*				nil	"description"	)
	(defvar		*HPS_DNA_HYPOTHESIS_END*					nil	"description"	)
	(defvar		*HPS_DNA_HYPOTHESIS_START*					nil	"description"	)
	(defvar		*HPS_DNA_INPUT_DATASET*						nil	"description"	)
	(defvar		*HPS_DNA_INPUTFILE*						nil	"description"	)
	(defvar		*HPS_DNA_INTERNAL_SUMMARY_REPORT*				nil	"description"	)
	(defvar		*HPS_DNA_LARGE_DIFF*						nil	"description"	)
	(defvar		*HPS_DNA_MAIN_REPORT_FILENAME*					nil	"description"	)
	(defvar		*HPS_DNA_MATCH_BEHAVIOR_FILENAME*				nil	"description"	)
	(defvar		*HPS_DNA_MATCH_EPSILON*						nil	"description"	)
	(defvar		*HPS_DNA_MATCH_METRIC_SIGNAL*					nil	"description"	)
	(defvar		*HPS_DNA_MATCH_RATING_HIST_DATA*				nil	"description"	)
	(defvar		*HPS_DNA_MATCH_RATING_SIGNAL*					nil	"description"	)
	(defvar		*HPS_DNA_MATCHING_GOAL*						nil	"description"	)
	(defvar		*HPS_DNA_MATCHING_PERCENTAGE*					nil	"description"	)
	(defvar		*HPS_DNA_MATCHING_SEGMENTS*					nil	"description"	)
	(defvar		*HPS_DNA_MATCHING_SEGMENTS_AND_METRICS*				nil	"description"	)
	(defvar		*HPS_DNA_NBINS*							nil	"description"	)
	(defvar		*HPS_DNA_NORMALIZED_SCORE*					nil	"description"	)
	(defvar		*HPS_DNA_NUM_UNIQ_MATCHES*					nil	"description"	)
	(defvar		*HPS_DNA_OUTPUTDIR*						nil	"description"	)
	(defvar		*HPS_DNA_PATTERN_MATCHES_DATASET*				nil	"description"	)
	(defvar		*HPS_DNA_PIVOT_TIMEINDEX*					nil	"description"	)
	(defvar		*HPS_DNA_PNUM*							nil	"description"	)
	(defvar		*HPS_DNA_RELEVANT_SEGMENTS*					nil	"description"	)
	(defvar		*HPS_DNA_REMAINDER_TESTSEQ_WINDOW*				nil	"description"	)
	(defvar		*HPS_DNA_REPORTFILE*						nil	"description"	)
	(defvar		*HPS_DNA_SEG_GOALDUR*						nil	"description"	)
	(defvar		*HPS_DNA_SEG_MERGEDUR*						nil	"description"	)
	(defvar		*HPS_DNA_SEG_MINDUR*						nil	"description"	)
	(defvar		*HPS_DNA_SEG_THRESHOLDDUR*					nil	"description"	)
	(defvar		*HPS_DNA_SEGMENT_DURATION*					nil	"description"	)
	(defvar		*HPS_DNA_SEGTABLE_FILE*						nil	"description"	)
	(defvar		*HPS_DNA_SEGTABLES_FILENAME*					nil	"description"	)
	(defvar		*HPS_DNA_SHIFT_AMOUNT*						nil	"description"	)
	(defvar		*HPS_DNA_SIG_SEG*						nil	"description"	)
	(defvar		*HPS_DNA_SIGNATURE_DATASET*					nil	"description"	)
	(defvar		*HPS_DNA_SIGNATURE_DATASET_XYZ*					nil	"description"	)
	(defvar		*HPS_DNA_SIGNATURE_FIRST_TUPLE*					nil	"description"	)
	(defvar		*HPS_DNA_SIGNATURE_LAST_TUPLE*					nil	"description"	)
	(defvar		*HPS_DNA_SIGNATURE_SIZE*					nil	"description"	)
	(defvar		*HPS_DNA_SIZE_1DNA_PRINTOUT*					nil	"description"	)
	(defvar		*HPS_DNA_SMALL_DIFF*						nil	"description"	)
	(defvar		*HPS_DNA_TEMP_TUPLE*						nil	"description"	)
	(defvar		*HPS_DNA_TEST_SEQUENCE_REMAINDER*				nil	"description"	)
	(defvar		*HPS_DNA_TEST_SEQUENCE_TEMP*					nil	"description"	)
	(defvar		*HPS_DNA_TESTSEQUENCE_DATASET*					nil	"description"	)
	(defvar		*HPS_DNA_TESTSEQUENCE_DATASET_XYZ*				nil	"description"	)
	(defvar		*HPS_DNA_TESTSEQUENCE_FIRST_TUPLE*				nil	"description"	)
	(defvar		*HPS_DNA_TESTSEQUENCE_LAST_TUPLE*				nil	"description"	)
	(defvar		*HPS_DNA_TESTSEQUENCE_SIZE*					nil	"description"	)
	(defvar		*HPS_DNA_XREF_COARSE_TRACKER_TIMESERIES*			nil	"description"	)
	(defvar		*HPS_ENDFLAG*							nil	"description"	)
	(defvar		*HPS_ENDPOINTS_MATCHES_IN_TIME*					nil	"description"	)
	(defvar		*HPS_EPSILON*							nil	"description"	)
	(defvar		*HPS_ERROR_FAST*						nil	"description"	)
	(defvar		*HPS_ERROR_FAST_STACK*						nil	"description"	)
	(defvar		*HPS_ERROR_REAL*						nil	"description"	)
	(defvar		*HPS_ERROR_REAL_STACK*						nil	"description"	)
	(defvar		*HPS_ERROR_SLOW*						nil	"description"	)
	(defvar		*HPS_ERROR_SLOW_STACK*						nil	"description"	)
	(defvar		*HPS_ERROR_TUPLE*						nil	"description"	)
	(defvar		*HPS_ERRORCORR_FORM*						nil	"description"	)
	(defvar		*HPS_ERRORCORR_SSE_I*						nil	"description"	)
	(defvar		*HPS_FAST_ERROR_MEAN*						nil	"description"	)
	(defvar		*HPS_FAST_ERROR_STDD*						nil	"description"	)
	(defvar		*HPS_FEEDBACK_MESSAGE*						nil	"description"	)
	(defvar		*HPS_FIELDDESCRIPTOR_ARRAY*					nil	"description"	)
	(defvar		*HPS_FILENAME_FOR_ITERATION*					nil	"description"	)
	(defvar		*HPS_FILENAME_INDEX*						nil	"description"	)
	(defvar		*HPS_FILENAME_TEMP*						nil	"description"	)
	(defvar		*HPS_FILENAME_TEMP_INDEX*					nil	"description"	)
	(defvar		*HPS_FILLER_SIZE*						nil	"description"	)
	(defvar		*HPS_FIT_COMMANDS*						nil	"description"	)
	(defvar		*HPS_FIT_LABELS*						nil	"description"	)
	(defvar		*HPS_FIXED_STACK_LIMIT*						nil	"description"	)
	(defvar		*HPS_FIXED_STACK_BIGLIMIT*					nil	"description"	)
	(defvar		*HPS_FORECAST_WINDOW*						nil	"description"	)
	(defvar		*HPS_FORECAST_WINSIZE*						nil	"description"	)
	(defvar		*HPS_FRACTALITY*						nil	"description"	)
	(defvar		*HPS_FRAME_END*							nil	"description"	)
	(defvar		*HPS_FRAME_START*						nil	"description"	)
	(defvar		*HPS_FULL_OUTPUT_MODE*						nil	"description"	)
	(defvar		*HPS_GLOBAL_COMPUTATION_STATE*					nil	"description"	)
	(defvar		*HPS_HIST_EPSILON*						nil	"description"	)
	(defvar		*HPS_HIST_ITER*							nil	"description"	)
	(defvar		*HPS_HIST_OUTPUT_FILE*						nil	"description"	)
	(defvar		*HPS_HIST_SUM_Y*						nil	"description"	)
	(defvar		*HPS_HIST_SUM_Y_PROB*						nil	"description"	)
	(defvar		*HPS_HIST_SUM_Y_TOTAL*						nil	"description"	)
	(defvar		*HPS_HIST_X*							nil	"description"	)
	(defvar		*HPS_HIST_Y*							nil	"description"	)
	(defvar		*HPS_HIST_Y_PROB*						nil	"description"	)
	(defvar		*HPS_HISTOGRAM_ARRAY*						nil	"description"	)
	(defvar		*HPS_HISTOGRAM_ASCII_TEMP*					nil	"description"	)
	(defvar		*HPS_HISTOGRAM_DATASET*						nil	"description"	)
	(defvar		*HPS_HISTOGRAM_INDEX_HIGH*					nil	"description"	)
	(defvar		*HPS_HISTOGRAM_INDEX_LOW*					nil	"description"	)
	(defvar		*HPS_HISTOGRAM_INTSTARTS*					nil	"description"	)
	(defvar		*HPS_HISTOGRAM_INTVALUES*					nil	"description"	)
	(defvar		*HPS_HISTOGRAM_LASTITEM*					nil	"description"	)
	(defvar		*HPS_HISTOGRAM_MAX*						nil	"description"	)
	(defvar		*HPS_HISTOGRAM_MIN*						nil	"description"	)
	(defvar		*HPS_HISTOGRAM_NBINS*						nil	"description"	)
	(defvar		*HPS_HISTOGRAM_RANGEELEMS_STACK*				nil	"description"	)
	(defvar		*HPS_HISTOGRAM_RANGEHIGH_STACK*					nil	"description"	)
	(defvar		*HPS_HISTOGRAM_RANGELOW_STACK*					nil	"description"	)
	(defvar		*HPS_HISTOGRAM_RANGESIZE_STACK*					nil	"description"	)
	(defvar		*HPS_HISTOGRAM_RANGETEMP*					nil	"description"	)
	(defvar		*HPS_HISTOGRAM_STACK*						nil	"description"	)
	(defvar		*HPS_HISTOGRAM_STEPSIZE*					nil	"description"	)
	(defvar		*HPS_HISTOGRAM_TS*						nil	"description"	)
	(defvar		*HPS_HISTOGRAM_TS_1*						nil	"description"	)
	(defvar		*HPS_HISTOGRAM_TS_2_SUBSET*					nil	"description"	)
	(defvar		*HPS_HISTOGRAM_TS_3*						nil	"description"	)
	(defvar		*HPS_HISTOGRAM_TUPLE*						nil	"description"	)
	(defvar		*HPS_HISTOGRAM_TUPLE_HIGH*					nil	"description"	)
	(defvar		*HPS_HISTOGRAM_TUPLE_LENGTH*					nil	"description"	)
	(defvar		*HPS_HISTOGRAM_TUPLE_LOW*					nil	"description"	)
	(defvar		*HPS_HTML_FOOTER*						nil	"description"	)
	(defvar		*HPS_HTML_HEADER*						nil	"description"	)
	(defvar		*HPS_INDEX*							nil	"description"	)
	(defvar		*HPS_INDEX_END*							nil	"description"	)
	(defvar		*HPS_INDEX_PRESENT*						nil	"description"	)
	(defvar		*HPS_INDEX_RECPAST*						nil	"description"	)
	(defvar		*HPS_INDEX_SIGNATURE_END*					nil	"description"	)
	(defvar		*HPS_INDEX_SIGNATURE_START*					nil	"description"	)
	(defvar		*HPS_INDEX_START*						nil	"description"	)
	(defvar		*HPS_INDEX_TESTSEQUENCE_END*					nil	"description"	)
	(defvar		*HPS_INDEX_TESTSEQUENCE_START*					nil	"description"	)
	(defvar		*HPS_INITIAL_RMEAN*						nil	"description"	)
	(defvar		*HPS_INPUT_ARRAY*						nil	"description"	)
	(defvar		*HPS_INPUT_DIRECTORY*						nil	"description"	)
	(defvar		*HPS_INPUT_PATH*						nil	"description"	)
	(defvar		*HPS_INPUT_SERIES*						nil	"description"	)
	(defvar		*HPS_INPUT_TIMESERIES*						nil	"description"	)
	(defvar		*HPS_INPUT_TIMESERIES_DATA*					nil	"description"	)
	(defvar		*HPS_INPUT_TIMESERIES_DATASET*					nil	"description"	)
	(defvar		*HPS_INPUT_TIMESERIES_FILENAME*					nil	"description"	)
	(defvar		*HPS_INPUT_TIMESERIES_HEAD*					nil	"description"	)
	(defvar		*HPS_INPUT_TIMESERIES_HEADER*					nil	"description"	)
	(defvar		*HPS_INPUT_TIMESERIES_INDEX*					nil	"description"	)
	(defvar		*HPS_INPUT_TIMESERIES_INDX*					nil	"description"	)
	(defvar		*HPS_INPUT_TIMESERIES_TUPLES*					nil	"description"	)
	(defvar		*HPS_INPUT_TS_TUPLESET*						nil	"description"	)
	(defvar		*HPS_INTERNAL_BUFFER*						nil	"description"	)
	(defvar		*HPS_IRREDUCEABILITY*						nil	"description"	)
	(defvar		*HPS_ITER*							nil	"description"	)
	(defvar		*HPS_ITERATION*							nil	"description"	)
	(defvar		*HPS_ITERATION_TEMP*						nil	"description"	)
	(defvar		*HPS_K*								nil	"description"	)
	(defvar		*HPS_LAMBDA*							nil	"description"	)
	(defvar		*HPS_LAMBDA_AT_ENDPOINTS_TS*					nil	"description"	)
	(defvar		*HPS_LAMBDASTACK*						nil	"description"	)
	(defvar		*HPS_LARGESEG_AVG_DURATION*					nil	"description"	)
	(defvar		*HPS_LARGESEG_FRACTALITY*					nil	"description"	)
	(defvar		*HPS_LARGESEG_STATIONARITY*					nil	"description"	)
	(defvar		*HPS_LCL*							nil	"description"	)
	(defvar		*HPS_LCL_MP*							nil	"description"	)
	(defvar		*HPS_M*								nil	"description"	)
	(defvar		*HPS_MAX_NVAL*							nil	"description"	)
	(defvar		*HPS_MAX_SEGMENT_DURATION*					nil	"description"	)
	(defvar		*HPS_MAXIMUM_SEGMENT_DURATION*					nil	"description"	)
	(defvar		*HPS_MAXIMUM_TUPLECAPACITY*					nil	"description"	)
	(defvar		*HPS_MEAN_DIFF*							nil	"description"	)
	(defvar		*HPS_MEAN_FORECAST_WINDOW*					nil	"description"	)
	(defvar		*HPS_MEAN_M*							nil	"description"	)
	(defvar		*HPS_MEAN_M_TRUNCATED*						nil	"description"	)
	(defvar		*HPS_MEAN_MP*							nil	"description"	)
	(defvar		*HPS_MEAN_OUTLIER_CLIPPING*					nil	"description"	)
	(defvar		*HPS_MEAN_OUTLIER_CLIPPING_INSEGS*				nil	"description"	)
	(defvar		*HPS_MEDIAN_MP*							nil	"description"	)
	(defvar		*HPS_MP*							nil	"description"	)
	(defvar		*HPS_MSE_BOUND*							nil	"description"	)
	(defvar		*HPS_MSE_BOUND_0*						nil	"description"	)
	(defvar		*HPS_MSE_BOUND_0_MEAN_ERRORCORR*				nil	"description"	)
	(defvar		*HPS_MSE_BOUND_0_MEAN_ERRORCORR_SUM*				nil	"description"	)
	(defvar		*HPS_MSE_BOUND_0_MEAN_TMAX_FORM*				nil	"description"	)
	(defvar		*HPS_MSE_BOUND_0_WINDOW*					nil	"description"	)
	(defvar		*HPS_MSE_BOUND_1*						nil	"description"	)
	(defvar		*HPS_MSE_BOUND_1_MEAN_POOLEDSTD*				nil	"description"	)
	(defvar		*HPS_MSE_BOUND_1_MEAN_POOLEDSTD_SUM*				nil	"description"	)
	(defvar		*HPS_MSE_BOUND_1_WINDOW*					nil	"description"	)
	(defvar		*HPS_MSE_BOUND_INSTANT*						nil	"description"	)
	(defvar		*HPS_MSE_BOUND_SEGMENT*						nil	"description"	)
	(defvar		*HPS_MSE_BOUND_STACK*						nil	"description"	)
	(defvar		*HPS_MSE_BOUND_WINDOW*						nil	"description"	)
	(defvar		*HPS_MSE_DIVIDER*						nil	"description"	)
	(defvar		*HPS_MSE_ERRORCORR_STACK*					nil	"description"	)
	(defvar		*HPS_MSE_MAX*							nil	"description"	)
	(defvar		*HPS_MSE_MEAN_FORSEG*						nil	"description"	)
	(defvar		*HPS_MSE_MEAN_OVERALL*						nil	"description"	)
	(defvar		*HPS_MSE_METRIC_INSTANT*					nil	"description"	)
	(defvar		*HPS_MSE_METRIC_SEGMENT*					nil	"description"	)
	(defvar		*HPS_MSE_METRIC_SEGMENT_SUM*					nil	"description"	)
	(defvar		*HPS_MSE_METRIC_WINDOW*						nil	"description"	)
	(defvar		*HPS_MSE_METRIC_WINDOW_SUM*					nil	"description"	)
	(defvar		*HPS_MSE_POOLED_STD_STACK*					nil	"description"	)
	(defvar		*HPS_MSE_STDD_FORSEG*						nil	"description"	)
	(defvar		*HPS_MSE_STDD_OVERALL*						nil	"description"	)
	(defvar		*HPS_MSE_TOTAL_FORSEG*						nil	"description"	)
	(defvar		*HPS_MSE_TOTAL_OVERALL*						nil	"description"	)
	(defvar		*HPS_MSEBOUND_RESETS_DENSITY*					nil	"description"	)
	(defvar		*HPS_MULTIV_DECISION_SIGNAL_TS*					nil	"description"	)
	(defvar		*HPS_MUTATE_SIGNATURE*						nil	"description"	)
	(defvar		*HPS_MUTATION_RATIO*						nil	"description"	)
	(defvar		*HPS_N_UPPER_LIMIT*						nil	"description"	)
	(defvar		*HPS_NEW_DECISION_BIT*						nil	"description"	)
	(defvar		*HPS_NEW_FORECAST*						nil	"description"	)
	(defvar		*HPS_NON_TRIVIAL_SEGMENTS*					nil	"description"	)
	(defvar		*HPS_NUM_MSEBOUND_RESETS*					nil	"description"	)
	(defvar		*HPS_NUM_SAMPLES*						nil	"description"	)
	(defvar		*HPS_NUM_SEGBOUND_RESETS*					nil	"description"	)
	(defvar		*HPS_NUMBER_OUTLIERS*						nil	"description"	)
	(defvar		*HPS_NUMBER_OUTLIERS_DENSITY*					nil	"description"	)
	(defvar		*HPS_NUMBER_OUTLIERS_INSEGS*					nil	"description"	)
	(defvar		*HPS_NVAL*							nil	"description"	)
	(defvar		*HPS_NVAL_3DNA_CODING*						nil	"description"	)
	(defvar		*HPS_OLD_ATS_SEGMENT_START_INDEX*				nil	"description"	)
	(defvar		*HPS_OLD_DECISION_BIT*						nil	"description"	)
	(defvar		*HPS_OLD_FORECAST*						nil	"description"	)
	(defvar		*HPS_ORIGINAL_LAMBDA_TS*					nil	"description"	)
	(defvar		*HPS_ORIGINAL_SAMPLE*						nil	"description"	)
	(defvar		*HPS_OUTLIER_DENSITY_INSEGS*					nil	"description"	)
	(defvar		*hps_outlier_tuple*						nil	"description"	)
	(defvar		*HPS_OUTPUT_DATASET_FILENAME*					nil	"description"	)
	(defvar		*HPS_OUTPUT_DIRECTORY*						nil	"description"	)
	(defvar		*HPS_OUTPUT_ENABLER*						nil	"description"	)
	(defvar		*HPS_OUTPUT_FILE*						nil	"description"	)
	(defvar		*HPS_OUTPUT_FILE_FIELDLABEL*					nil	"description"	)
	(defvar		*HPS_OUTPUT_FILE_HEADER*					nil	"description"	)
	(defvar		*HPS_OUTPUT_FILE_HEADER_0*					nil	"description"	)
	(defvar		*HPS_OUTPUT_FILE_HEADER_1*					nil	"description"	)
	(defvar		*HPS_OUTPUT_FILE_HEADER_10*					nil	"description"	)
	(defvar		*HPS_OUTPUT_FILE_HEADER_2*					nil	"description"	)
	(defvar		*HPS_OUTPUT_FILE_HEADER_3*					nil	"description"	)
	(defvar		*HPS_OUTPUT_FILE_HEADER_4*					nil	"description"	)
	(defvar		*HPS_OUTPUT_FILE_HEADER_5*					nil	"description"	)
	(defvar		*HPS_OUTPUT_FILE_HEADER_6*					nil	"description"	)
	(defvar		*HPS_OUTPUT_FILE_HEADER_7*					nil	"description"	)
	(defvar		*HPS_OUTPUT_FILE_HEADER_8*					nil	"description"	)
	(defvar		*HPS_OUTPUT_FILE_HEADER_9*					nil	"description"	)
	(defvar		*HPS_OUTPUT_MINOR_TICK*						nil	"description"	)
	(defvar		*HPS_OUTPUT_MODE*						nil	"description"	)
	(defvar		*HPS_OUTPUT_PATH*						nil	"description"	)
	(defvar		*HPS_OUTPUT_REPORT_FILENAME*					nil	"description"	)
	(defvar		*HPS_OUTPUT_TIMESERIES_FILENAME*				nil	"description"	)
	(defvar		*HPS_OUTPUTMODE*						nil	"description"	)
	(defvar		*HPS_PARAMETER_FIELDS*						nil	"description"	)
	(defvar		*HPS_PARAMETER_VALUES*						nil	"description"	)
	(defvar		*HPS_PATTERN_MATCH_DATASET*					nil	"description"	)
	(defvar		*HPS_PCO_MEAN_FORSEG*						nil	"description"	)
	(defvar		*HPS_PCO_MEAN_OVERALL*						nil	"description"	)
	(defvar		*HPS_PCO_STDD_FORSEG*						nil	"description"	)
	(defvar		*HPS_PCO_STDD_OVERALL*						nil	"description"	)
	(defvar		*HPS_PERF_E_RELAT_I*						nil	"description"	)
	(defvar		*HPS_PERF_F_S_RAT_I*						nil	"description"	)
	(defvar		*HPS_PERF_N_SAMPL_I*						nil	"description"	)
	(defvar		*HPS_PERF_P_MUCOR_I*						nil	"description"	)
	(defvar		*HPS_PERF_Z_ERROR_I*						nil	"description"	)
	(defvar		*HPS_POOLED_STD*						nil	"description"	)
	(defvar		*HPS_POOLED_STD_MEAN*						nil	"description"	)
	(defvar		*HPS_POOLED_STD_WINDOW*						nil	"description"	)
	(defvar		*HPS_POOLED_VAR*						nil	"description"	)
	(defvar		*HPS_POOLED_VAR_COMP*						nil	"description"	)
	(defvar		*HPS_POOLED_VAR_MAIN*						nil	"description"	)
	(defvar		*HPS_PREVIOUSLAMBDA*						nil	"description"	)
	(defvar		*HPS_PRINT_ITER*						nil	"description"	)
	(defvar		*HPS_PRINT_SPECIAL_BLANK_MARKER*				nil	"description"	)
	(defvar		*HPS_PRINTDUMPSIZE*						nil	"description"	)
	(defvar		*HPS_RANDOM_RANGE_LIMIT*					nil	"description"	)
	(defvar		*HPS_REAL_ERROR_MEAN*						nil	"description"	)
	(defvar		*HPS_REAL_ERROR_MEAN_SEGSET*					nil	"description"	)
	(defvar		*HPS_REAL_ERROR_STDD*						nil	"description"	)
	(defvar		*HPS_REAL_ERROR_STDD_SEGSET*					nil	"description"	)
	(defvar		*HPS_RELT_ERROR_MEAN*						nil	"description"	)
	(defvar		*HPS_RELT_ERROR_MEAN_SEGSET*					nil	"description"	)
	(defvar		*HPS_RELT_ERROR_STDD*						nil	"description"	)
	(defvar		*HPS_RELT_ERROR_STDD_SEGSET*					nil	"description"	)
	(defvar		*HPS_REPRESENTATION_SIZE*					nil	"description"	)
	(defvar		*HPS_SEARCH_TEMP*						nil	"description"	)
	(defvar		*HPS_SEG_DIFF*							nil	"description"	)
	(defvar		*HPS_SEGMENT_ENDP_IDENTIFIER_TS*				nil	"description"	)
	(defvar		*HPS_SIGNATURE_FROM_INDEX*					nil	"description"	)
	(defvar		*HPS_SIGNATURE_TO_INDEX*					nil	"description"	)
	(defvar		*HPS_SIGNATURESEQ_NUM*						nil	"description"	)
	(defvar		*HPS_SIGNIFICANT_SEGMENTS*					nil	"description"	)
	(defvar		*HPS_SLOW_ERROR_MEAN*						nil	"description"	)
	(defvar		*HPS_SLOW_ERROR_STDD*						nil	"description"	)
	(defvar		*HPS_SMALL_FRACTION*						nil	"description"	)
	(defvar		*HPS_SORTED_HISTOGRAM_SERIES*					nil	"description"	)
	(defvar		*HPS_SSE_FORM_STACK*						nil	"description"	)
	(defvar		*HPS_SSE_WINDOW*						nil	"description"	)
	(defvar		*HPS_START_BUILDUPDELAY*					nil	"description"	)
	(defvar		*HPS_STATE_CHANGE*						nil	"description"	)
	(defvar		*HPS_STATIONARITY*						nil	"description"	)
	(defvar		*HPS_STATS_OUTPUT_FILE*						nil	"description"	)
	(defvar		*HPS_STATS_OUTPUT-STREAM*					nil	"description"	)
	(defvar		*HPS_STD_M*							nil	"description"	)
	(defvar		*HPS_STD_M_TRUNCATED*						nil	"description"	)
	(defvar		*HPS_STD_MP*							nil	"description"	)
	(defvar		*HPS_STENO_GNUPLOT_CMDFILE*					nil	"description"	)
	(defvar		*HPS_SUBMSG_TEMP*						nil	"description"	)
	(defvar		*HPS_SUBSEQ_FILENAME*						nil	"description"	)
	(defvar		*HPS_SUBSEQ_FILENAME_TEMP*					nil	"description"	)
	(defvar		*HPS_SUBSEQUENCE_SIZE*						nil	"description"	)
	(defvar		*HPS_SYSTEM_CMDS*						nil	"description"	)
	(defvar		*HPS_SZS_MEAN_FORSEG*						nil	"description"	)
	(defvar		*HPS_SZS_MEAN_OVERALL*						nil	"description"	)
	(defvar		*HPS_SZS_STDD_FORSEG*						nil	"description"	)
	(defvar		*HPS_SZS_STDD_OVERALL*						nil	"description"	)
	(defvar		*HPS_T_DF*							nil	"description"	)
	(defvar		*HPS_TEMP_FIELD*						nil	"description"	)
	(defvar		*HPS_TEMP_FRAME*						nil	"description"	)
	(defvar		*HPS_TEMP_KLUDGE*						nil	"description"	)
	(defvar		*HPS_TEMP_KLUDGE_INF*						nil	"description"	)
	(defvar		*HPS_TEMP_KLUDGE_ONE*						nil	"description"	)
	(defvar		*HPS_TEMP_KLUDGE_ZERO*						nil	"description"	)
	(defvar		*HPS_TEMP_MIDPOINT*						nil	"description"	)
	(defvar		*HPS_TEMP_MSSE*							nil	"description"	)
	(defvar		*HPS_TEMP_NVAL*							nil	"description"	)
	(defvar		*HPS_TEMP_PERF_COVWINDOW*					nil	"description"	)
	(defvar		*HPS_TEMP_PERF_COVWINDOW_MEAN_MP*				nil	"description"	)
	(defvar		*HPS_TEMP_PERF_DIVIDER*						nil	"description"	)
	(defvar		*HPS_TEMP_PERF_ERROR_MEAN*					nil	"description"	)
	(defvar		*HPS_TEMP_PERF_ERROR_SAMPLE*					nil	"description"	)
	(defvar		*HPS_TEMP_PERF_ERROR_STD*					nil	"description"	)
	(defvar		*HPS_TEMP_PERF_ERROR_WINDOW*					nil	"description"	)
	(defvar		*HPS_TEMP_PERF_MAXVAR*						nil	"description"	)
	(defvar		*HPS_TEMP_PERF_MINVAR*						nil	"description"	)
	(defvar		*HPS_TEMP_PERF_NVAL*						nil	"description"	)
	(defvar		*HPS_TEMP_PERF_STD_DIVIDER*					nil	"description"	)
	(defvar		*HPS_TEMP_PERF_TRUNCATED_WINDOW_M*				nil	"description"	)
	(defvar		*HPS_TEMP_PRINT_STATVALUE*					nil	"description"	)
	(defvar		*HPS_TEMP_PRINT_VAR*						nil	"description"	)
	(defvar		*HPS_TEMP_SE*							nil	"description"	)
	(defvar		*HPS_TEMP_SERIES*						nil	"description"	)
	(defvar		*HPS_TEMP_SOSE*							nil	"description"	)
	(defvar		*HPS_TEMP_SUBLIST*						nil	"description"	)
	(defvar		*HPS_TEMP_SUM*							nil	"description"	)
	(defvar		*HPS_TEMP_WINDOW*						nil	"description"	)
	(defvar		*HPS_TEMP_WINDOW_SORTED*					nil	"description"	)
	(defvar		*HPS_TEMP_WSIZE*						nil	"description"	)
	(defvar		*HPS_TESTSEQUENCE_NUM*						nil	"description"	)
	(defvar		*HPS_TIMESERIES*						nil	"description"	)
	(defvar		*HPS_TIMESERIES_DATASET*					nil	"description"	)
	(defvar		*HPS_TIMESERIES_INPUT_FILE*					nil	"description"	)
	(defvar		*HPS_TIMESHIFT*							nil	"description"	)
	(defvar		*HPS_TMAX*							nil	"description"	)
	(defvar		*HPS_TRANSFORM_OUTLIER_LCL*					nil	"description"	)
	(defvar		*HPS_TRANSFORM_OUTLIER_UCL*					nil	"description"	)
	(defvar		*HPS_TRANSFORMED_ERROR_DATASET*					nil	"description"	)
	(defvar		*HPS_TRANSFORMED_ERROR_TS*					nil	"description"	)
	(defvar		*HPS_TRANSFORMED_MONITOR_TS*					nil	"description"	)
	(defvar		*HPS_TRANSFORMED_OUTLIER_DATASET*				nil	"description"	)
	(defvar		*HPS_TRANSFORMED_OUTLIER_TS*					nil	"description"	)
	(defvar		*HPS_TRANSFORMED_RESPONSE_DATASET*				nil	"description"	)
	(defvar		*HPS_TRIM_HIGH*							nil	"description"	)
	(defvar		*HPS_TRIM_LOW*							nil	"description"	)
	(defvar		*HPS_TRUNCATED_HISTOGRAM_SERIES*				nil	"description"	)
	(defvar		*HPS_TTABLE*							nil	"description"	)
	(defvar		*HPS_TTABLE_COLS*						nil	"description"	)
	(defvar		*HPS_TTABLE_FILE*						nil	"description"	)
	(defvar		*HPS_TTABLE_HEADER*						nil	"description"	)
	(defvar		*HPS_TTABLE_ROW*						nil	"description"	)
	(defvar		*HPS_TTABLE_ROWS*						nil	"description"	)
	(defvar		*HPS_TTEST*							nil	"description"	)
	(defvar		*HPS_TUPLE*							nil	"description"	)
	(defvar		*HPS_TVAL*							nil	"description"	)
	(defvar		*HPS_UCL*							nil	"description"	)
	(defvar		*HPS_UCL_MP*							nil	"description"	)
	(defvar		*HPS_USABLE_ERROR_STACKSIZE*					nil	"description"	)
	(defvar		*HPS_USABLE_STACKSIZE*						nil	"description"	)
	(defvar		*HPS_USABLE_STACKSIZE_LAMBDA*					nil	"description"	)
	(defvar		*HPS_USABLE_STATIONARITY*					nil	"description"	)
	(defvar		*HPS_VALID_RANGES*						nil	"description"	)
	(defvar		*HPS_VALUE*							nil	"description"	)
	(defvar		*HPS_VAR_M*							nil	"description"	)
	(defvar		*HPS_VAR_MP*							nil	"description"	)
	(defvar		*HPS_WINDOW_M*							nil	"description"	)
	(defvar		*HPS_WINDOW_MP*							nil	"description"	)
	(defvar		*HPS_WINEND_M*							nil	"description"	)
	(defvar		*HPS_WINEND_MP*							nil	"description"	)
	(defvar		*HPS_WINSTART_M*						nil	"description"	)
	(defvar		*HPS_WINSTART_MP*						nil	"description"	)
	(defvar		*HPS_XCOLUMN*							nil	"description"	)
	(defvar		*HPS_XVALS*							nil	"description"	)
	(defvar		*HPS_YCOLUMN*							nil	"description"	)
	(defvar  	*HPS_HEADERROW*							nil	"description"	)
	(defvar		*HPS_YVALS*							nil	"description"	)
	(defvar		*HPSDEBUG*							nil	"description"	)
	(defvar		*HPSTUPLE*							nil	"description"	)
	(defvar		*ITER*								nil	"description"	)
	(defvar		*LAST_MATCH*							nil	"description"	)
	(defvar		*LAST_MATCHING_SEG*						nil	"description"	)
	(defvar		*LAST_MATCHING_SEGMENT_AND_METRICS*				nil	"description"	)
	(defvar		*LAST_MATCHING_SEGMENT_QUALITY*					nil	"description"	)
	(defvar		*LAST_SIGNATURE_SEGMENT*					nil	"description"	)
	(defvar		*LASTHPS_SEG_DIFF*						nil	"description"	)
	(defvar		*MATCH_DETAILS*							nil	"description"	)
	(defvar		*MATCH_FITNESS*							nil	"description"	)
	(defvar		*MATCH_QUALITY*							nil	"description"	)
	(defvar		*MATCH_SEGMENT*							nil	"description"	)
	(defvar		*MATCHING_SEGMENT_AND_METRICS*					nil	"description"	)
	(defvar		*MATCHING_TUPLE*						nil	"description"	)
	(defvar		*MINIMUM_DIST*							nil	"description"	)
	(defvar		*NUM_APPRXMATCH*						nil	"description"	)
	(defvar		*NUM_APPRXMISPL*						nil	"description"	)
	(defvar		*NUM_EXACTMATCH*						nil	"description"	)
	(defvar		*NUM_EXACTMISPL*						nil	"description"	)
	(defvar		*NUM_LOOSEMATCH*						nil	"description"	)
	(defvar		*NUM_LOOSEMISPL*						nil	"description"	)
	(defvar		*NUM_NOMATCHFND*						nil	"description"	)
	(defvar		*NUM_SPANNMATCH*						nil	"description"	)
	(defvar		*NUM_SPANNMISPL*						nil	"description"	)
	(defvar		*NVAL_TEMP*							nil	"description"	)
	(defvar		*PARK-MILLER-SEED*						nil	"description"	)
	(defvar		*SIGNATURE_SEGMENT*						nil	"description"	)
	(defvar		*STENO_ALPHABETDESCR*						nil	"description"	)
	(defvar		*STENO_BASEDIR*							nil	"description"	)
	(defvar		*STENO_CODE*							nil	"description"	)
	(defvar		*STENO_CYPHERDESCR*						nil	"description"	)
	(defvar		*STENO_DECODED_MSG*						nil	"description"	)
	(defvar		*STENO_EVEN_GAP_MODE*						nil	"description"	)
	(defvar		*STENO_HEADER_ROW_TEMP*						nil	"description"	)
	(defvar		*STENO_HPS_APPROX_TUPLESET*					nil	"description"	)
	(defvar		*STENO_HPS_NOISE_FACTOR*					nil	"description"	)
	(defvar		*STENO_HPS_NOISE_RANGE*						nil	"description"	)
	(defvar		*STENO_HPS_RAND_NVAL*						nil	"description"	)
	(defvar		*STENO_HPS_RANDOM_NVAL_PLUSX*					nil	"description"	)
	(defvar		*STENO_HPS_SERIES*						nil	"description"	)
	(defvar		*STENO_HPS_SERIES_TEMP*						nil	"description"	)
	(defvar		*STENO_HPS_TUPLESET*						nil	"description"	)
	(defvar		*STENO_INPUTLIST*						nil	"description"	)
	(defvar		*STENO_ITER*							nil	"description"	)
	(defvar		*STENO_ITER_TEMP*						nil	"description"	)
	(defvar		*STENO_MAPALPHABET*						nil	"description"	)
	(defvar		*STENO_MAPCODE*							nil	"description"	)
	(defvar		*STENO_MAPDICT*							nil	"description"	)
	(defvar		*STENO_MAPHALF*							nil	"description"	)
	(defvar		*STENO_MAPHIGH*							nil	"description"	)
	(defvar		*STENO_MAPHIGH_LOWEND*						nil	"description"	)
	(defvar		*STENO_MAPLOW*							nil	"description"	)
	(defvar		*STENO_MAPRESULT*						nil	"description"	)
	(defvar		*STENO_MAPSIZE*							nil	"description"	)
	(defvar		*STENO_MISPELLING_CODE*						nil	"description"	)
	(defvar		*STENO_MSG*							nil	"description"	)
	(defvar		*STENO_NEW_SEGMENT_FLAG*					nil	"description"	)
	(defvar		*STENO_NUM_ITEMS*						nil	"description"	)
	(defvar		*STENO_NVAL*							nil	"description"	)
	(defvar		*STENO_NVAL_DIFF*						nil	"description"	)
	(defvar		*STENO_NVAL_SIGN_ALTERN*					nil	"description"	)
	(defvar		*STENO_OUTPUT_FILENAME*						nil	"description"	)
	(defvar		*STENO_OUTPUTDIR*						nil	"description"	)
	(defvar		*STENO_RAND_ITER*						nil	"description"	)
	(defvar		*STENO_RANDOM_INDEX*						nil	"description"	)
	(defvar		*STENO_RANDOM_LIMIT*						nil	"description"	)
	(defvar		*STENO_RANDOM_UNIFORM_VAL*					nil	"description"	)
	(defvar		*STENO_RANDOM_VAL*						nil	"description"	)
	(defvar		*STENO_RANDOMVALUES_ARRAY*					nil	"description"	)
	(defvar		*STENO_RANDOMVALUES_SERIES*					nil	"description"	)
	(defvar		*STENO_REPORTFILE*						nil	"description"	)
	(defvar		*STENO_REVERSEDMAPDICT*						nil	"description"	)
	(defvar		*STENO_SEG_AVGDUR*						nil	"description"	)
	(defvar		*STENO_SEG_AVGDURVAR*						nil	"description"	)
	(defvar		*STENO_SEG_CODE*						nil	"description"	)
	(defvar		*STENO_SEG_DUR*							nil	"description"	)
	(defvar		*STENO_SEG_DURATION*						nil	"description"	)
	(defvar		*STENO_SEG_DURNVAL*						nil	"description"	)
	(defvar		*STENO_SEG_END*							nil	"description"	)
	(defvar		*STENO_SEG_GAPDUR*						nil	"description"	)
	(defvar		*STENO_SEG_GAPMEAN*						nil	"description"	)
	(defvar		*STENO_SEG_GAPNVAL*						nil	"description"	)
	(defvar		*STENO_SEG_MEANDUR*						nil	"description"	)
	(defvar		*STENO_SEG_MINDUR*						nil	"description"	)
	(defvar		*STENO_SEG_NEXT_NVAL*						nil	"description"	)
	(defvar		*STENO_SEG_NITEMS_PER_LINE*					nil	"description"	)
	(defvar		*STENO_SEG_NVAL*						nil	"description"	)
	(defvar		*STENO_SEG_SIZE*						nil	"description"	)
	(defvar		*STENO_SEG_START*						nil	"description"	)
	(defvar		*STENO_SEG_TABLE*						nil	"description"	)
	(defvar		*STENO_SEG_TABLE_TEMP*						nil	"description"	)
	(defvar		*STENO_SIMILAR_EPSILON*						nil	"description"	)
	(defvar		*STENO_TOKENLIST*						nil	"description"	)
	(defvar		*STENO_TVAL*							nil	"description"	)
	(defvar		*TEMP_STENO_INPUTLIST*						nil	"description"	)
	(defvar		*TEMP_STENO_INPUTTEXT*						nil	"description"	)
	(defvar		*TEMP_STENO_INPUTTEXT_1*					nil	"description"	)
	(defvar		*TEMP_STENO_INPUTTEXT_2*					nil	"description"	)
	(defvar		*TEMP_STENO_INPUTTEXT_3*					nil	"description"	)
	(defvar		*TESTSEQ_SEGMENT*						nil	"description"	)
	(defvar		*THIS_MATCHING_SEG*						nil	"description"	)
	(defvar		*THRESHOLD_LIST_A*						nil	"description"	)
	(defvar		*THRESHOLD_LIST_B*						nil	"description"	)
	(defvar		_BREAK								nil	"description"	)
	(defvar		_DIV0								nil	"description"	)
	(defvar		_DIV1								nil	"description"	)
	(defvar		_HREF0								nil	"description"	)
	(defvar		_HREF1								nil	"description"	)
	(defvar		_PRE0								nil	"description"	)
	(defvar		_PRE1								nil	"description"	)
	(defvar		_TABLE0								nil	"description"	)
	(defvar		_TABLE1								nil	"description"	)
	(defvar		_TCOL0								nil	"description"	)
	(defvar		_TCOL0A								nil	"description"	)
	(defvar		_TCOL0B								nil	"description"	)
	(defvar		_TCOL0C								nil	"description"	)
	(defvar		_TCOL0D								nil	"description"	)
	(defvar		_TCOL0E								nil	"description"	)
	(defvar		_TCOL0X								nil	"description"	)
	(defvar		_TCOL0Z								nil	"description"	)
	(defvar		_TCOL1								nil	"description"	)
	(defvar		_TITLE0								nil	"description"	)
	(defvar		_TITLE1								nil	"description"	)
	(defvar		_TROW0								nil	"description"	)
	(defvar		_TROW1								nil	"description"	)
	(defvar		ALIST_TEMP							nil	"description"	)
	(defvar		ALPHABET							nil	"description"	)
	(defvar		AT_INDEX							nil	"description"	)
	(defvar		BEST_PATTERN_IN_REMAINDER					nil	"description"	)
	(defvar		BESTPAT								nil	"description"	)
	(defvar		COSTVECTOR							nil	"description"	)
	(defvar		COSTWEIGTH							nil	"description"	)
	(defvar		CURRENTVAL							nil	"description"	)
	(defvar		DF								nil	"description"	)
	(defvar		DIFF_ENOUGH							nil	"description"	)
	(defvar		DNA_BASE							nil	"description"	)
	(defvar		DNA_BASE_SEQUENCE						nil	"description"	)
	(defvar		DNA_FILE_CONTENTS						nil	"description"	)
	(defvar		DNA_FILE_CONTENTS_BUT_LASTONE					nil	"description"	)
	(defvar		DNA_FILE_LINE							nil	"description"	)
	(defvar		DNA_SEQUENCE							nil	"description"	)
	(defvar		DNA_SEQUENCE_LIST						nil	"description"	)
	(defvar		DNA_SEQUENCE_TEMP						nil	"description"	)
	(defvar		EXT_CALL_SOURCE							nil	"description"	)
	(defvar		EXTERNAL_CALL_FLAG						nil	"description"	)
	(defvar		FIELDNUM							nil	"description"	)
	(defvar		HIGH								nil	"description"	)
	(defvar		HIST_DATASET_TEMP						nil	"description"	)
	(defvar		HIST_LABELS							nil	"description"	)
	(defvar		HPS_1DNA_INDEX_FROM						nil	"description"	)
	(defvar		HPS_1DNA_INDEX_TO						nil	"description"	)
	(defvar		HPS_ALIGNMENT_INDEX						nil	"description"	)
	(defvar		HPS_AMP								nil	"description"	)
	(defvar		HPS_AMP_WO							nil	"description"	)
	(defvar		HPS_APPMODE							nil	"description"	)
	(defvar		HPS_BESTMATCHES_HEADER						nil	"description"	)
	(defvar		HPS_BIN_TUPLE							nil	"description"	)
	(defvar		HPS_BIN_TUPLE_WO						nil	"description"	)
	(defvar		HPS_DNA_BROAD_SEARCH_LEVEL					nil	"description"	)
	(defvar		HPS_DNA_DIFFERENCES						nil	"description"	)
	(defvar		HPS_DNA_FINEGRAIN_ALIGN_INDEX					nil	"description"	)
	(defvar		HPS_DNA_HTML_MAIN_ITEM_P1					nil	"description"	)
	(defvar		HPS_DNA_HTML_MAIN_ITEM_P2					nil	"description"	)
	(defvar		HPS_DNA_HTML_MAIN_ITEM_P3					nil	"description"	)
	(defvar		HPS_DNA_HTML_MAIN_ITEM_P4					nil	"description"	)
	(defvar		HPS_DNA_LARGE_FILESIZE						nil	"description"	)
	(defvar		HPS_DNA_MUTATION_RETVAL						nil	"description"	)
	(defvar		HPS_DNA_NUM_MATCHES_REQD					nil	"description"	)
	(defvar		HPS_DNA_NUMBER_DIFF						nil	"description"	)
	(defvar		HPS_DNA_NUMBER_RETRY_LEVELS					nil	"description"	)
	(defvar		HPS_ENDPOINTS_MATCH						nil	"description"	)
	(defvar		HPS_FIELD_LEN							nil	"description"	)
	(defvar		HPS_FIT_COMMANDS						nil	"description"	)
	(defvar		HPS_FIT_LABELS							nil	"description"	)
	(defvar		HPS_FOUND_NONTRIVIAL_MATCH					nil	"description"	)
	(defvar		HPS_GAUSSIAN_VALUE_FOR_X					nil	"description"	)
	(defvar		HPS_HEADERMSG							nil	"description"	)
	(defvar		HPS_HIST_LABELS							nil	"description"	)
	(defvar		HPS_HTML_FIXEDSIZE_MAPDESC_HEADER				nil	"description"	)
	(defvar		HPS_HTML_FIXEDSIZE_MAPPING_HEADER0				nil	"description"	)
	(defvar		HPS_HTML_FIXEDSIZE_MAPPING_HEADER1				nil	"description"	)
	(defvar		HPS_INTERSECTION						nil	"description"	)
	(defvar		HPS_ITER							nil	"description"	)
	(defvar		HPS_LINEAR_MATCH_RESULT						nil	"description"	)
	(defvar		HPS_MAPPED_SIG_SEG						nil	"description"	)
	(defvar		HPS_MAPPING_SET							nil	"description"	)
	(defvar		HPS_MATCH_HYP_END						nil	"description"	)
	(defvar		HPS_MATCH_HYP_START						nil	"description"	)
	(defvar		HPS_MATCH_MEAN_X						nil	"description"	)
	(defvar		HPS_MATCH_MEAN_X_WO						nil	"description"	)
	(defvar		HPS_MATCH_MEAN_Y						nil	"description"	)
	(defvar		HPS_MATCH_MEAN_Y_WO						nil	"description"	)
	(defvar		HPS_MATCH_P							nil	"description"	)
	(defvar		HPS_MATCH_RATING_WO						nil	"description"	)
	(defvar		HPS_MATCH_TITLE							nil	"description"	)
	(defvar		HPS_MATCHING_P							nil	"description"	)
	(defvar		HPS_MATCHING_P_END						nil	"description"	)
	(defvar		HPS_MATCHING_P_START						nil	"description"	)
	(defvar		HPS_MU								nil	"description"	)
	(defvar		HPS_MU_WO							nil	"description"	)
	(defvar		HPS_NEW_3DNA_ENCODING						nil	"description"	)
	(defvar		HPS_NEW_ITEM							nil	"description"	)
	(defvar		HPS_NOISE							nil	"description"	)
	(defvar		HPS_NUM_PATMATCHES						nil	"description"	)
	(defvar		HPS_NUMITERS							nil	"description"	)
	(defvar		HPS_NUMPATS							nil	"description"	)
	(defvar		HPS_ORIG_SUBSEQ							nil	"description"	)
	(defvar		HPS_PAT_RANGESET						nil	"description"	)
	(defvar		HPS_PAT_SEG							nil	"description"	)
	(defvar		HPS_PAT_SEGTABLE						nil	"description"	)
	(defvar		HPS_PAT_START							nil	"description"	)
	(defvar		HPS_PATNUM							nil	"description"	)
	(defvar		HPS_PATNUM_TEMP							nil	"description"	)
	(defvar		HPS_PIVOT_POINT							nil	"description"	)
	(defvar		HPS_POSITION_WITHIN						nil	"description"	)
	(defvar		HPS_RANK_P							nil	"description"	)
	(defvar		HPS_READER_ITER							nil	"description"	)
	(defvar		HPS_REALTIME_INDEX						nil	"description"	)
	(defvar		HPS_SEGLABELS_SDURS						nil	"description"	)
	(defvar		HPS_SEGLABELS_TVALS						nil	"description"	)
	(defvar		HPS_SEGTABLE_HEADER						nil	"description"	)
	(defvar		HPS_SIG_RANGESET						nil	"description"	)
	(defvar		HPS_SIG_SEG							nil	"description"	)
	(defvar		HPS_SIG_SEGTABLE						nil	"description"	)
	(defvar		HPS_SIG_SUBSEQ							nil	"description"	)
	(defvar		HPS_SIGMA							nil	"description"	)
	(defvar		HPS_SIGMA_WO							nil	"description"	)
	(defvar		HPS_SIGNATURE_LABEL						nil	"description"	)
	(defvar		HPS_SIGSEQ_TEMP							nil	"description"	)
	(defvar		HPS_SIZE_SIGNATURE						nil	"description"	)
	(defvar		HPS_SP								nil	"description"	)
	(defvar		HPS_STENO_MAIN_REPORT_DYNAMIC_CONTENTS				nil	"description"	)
	(defvar		HPS_STENO_MINSEGDUR_VALS					nil	"description"	)
	(defvar		HPS_STENO_SEGRATIO_GOAL						nil	"description"	)
	(defvar		HPS_STENO_SIGLEN_TO_INPUT_RATIO					nil	"description"	)
	(defvar		HPS_SUBSEQ_TEMP							nil	"description"	)
	(defvar		HPS_TESTSEQ_LABEL						nil	"description"	)
	(defvar		HPS_TESTSEQ_LEN							nil	"description"	)
	(defvar		HPS_TIMEINDEX_P							nil	"description"	)
	(defvar		HPS_TUPLE							nil	"description"	)
	(defvar		HPS_TUPLE_P							nil	"description"	)
	(defvar		HPS_UNBIASED_CODE						nil	"description"	)
	(defvar		HPS_VALID_INDEX							nil	"description"	)
	(defvar		HPS_VALID_RESULT						nil	"description"	)
	(defvar		HPS_WHICH_APPLICATION						nil	"description"	)
	(defvar		HTML_MULTIPLE_CELL_DESCRIPTOR					nil	"description"	)
	(defvar		HTML_SINGLE_CELL_DESCRIPTOR					nil	"description"	)
	(defvar		HYP_BASE_LABELS							nil	"description"	)
	(defvar		HYP_END								nil	"description"	)
	(defvar		HYP_LABEL_SDURS							nil	"description"	)
	(defvar		HYP_LABEL_TVALS							nil	"description"	)
	(defvar		HYP_MATCH_LABELS						nil	"description"	)
	(defvar		HYP_START							nil	"description"	)
	(defvar		ITER								nil	"description"	)
	(defvar		J								nil	"description"	)
	(defvar		LARGESEG_FRAGMENTER_ON						nil	"description"	)
	(defvar		LOW								nil	"description"	)
	(defvar		M_M								nil	"description"	)
	(defvar		M_R								nil	"description"	)
	(defvar		MAPCODE								nil	"description"	)
	(defvar		MAPPING_SET							nil	"description"	)
	(defvar		MATCH_QUALITY							nil	"description"	)
	(defvar		MATCHQUALITY							nil	"description"	)
	(defvar		NB1								nil	"description"	)
	(defvar		NB2								nil	"description"	)
	(defvar		NB3								nil	"description"	)
	(defvar		NEW-LIST							nil	"description"	)
	(defvar		NITEMSBIN							nil	"description"	)
	(defvar		NORMCOST							nil	"description"	)
	(defvar		NUM_MATCHING_PATTERNS						nil	"description"	)
	(defvar		NUMPATS								nil	"description"	)
	(defvar		OF_SIZE								nil	"description"	)
	(defvar		OLD_P_RATING							nil	"description"	)
	(defvar		ONEMINUSALPHA							nil	"description"	)
	(defvar		ORIG								nil	"description"	)
	(defvar		P								nil	"description"	)
	(defvar		P_END								nil	"description"	)
	(defvar		P_IDX								nil	"description"	)
	(defvar		P_RATING							nil	"description"	)
	(defvar		P_START								nil	"description"	)
	(defvar		PAT_ARROW							nil	"description"	)
	(defvar		PAT_LABEL							nil	"description"	)
	(defvar		PAT_RANK_TEMP							nil	"description"	)
	(defvar		PATNUM								nil	"description"	)
	(defvar		PATTERN								nil	"description"	)
	(defvar		PLOT_X								nil	"description"	)
	(defvar		PLOT_Y								nil	"description"	)
	(defvar		PRES_END							nil	"description"	)
	(defvar		PRES_START							nil	"description"	)
	(defvar		PREV_END							nil	"description"	)
	(defvar		PREV_START							nil	"description"	)
	(defvar		PREVIOUS_P							nil	"description"	)
	(defvar		REMAINDER							nil	"description"	)
	(defvar		S_M								nil	"description"	)
	(defvar		S_R								nil	"description"	)
	(defvar		SEG_CODE							nil	"description"	)
	(defvar		SEG_LABEL							nil	"description"	)
	(defvar		SEG_SDUR							nil	"description"	)
	(defvar		SEG_START							nil	"description"	)
	(defvar		SEG_TVAL							nil	"description"	)
	(defvar		SEGLABELS							nil	"description"	)
	(defvar		SEQUENCE_HREF							nil	"description"	)
	(defvar		STENO_HTML_MAIN_FOOTER						nil	"description"	)
	(defvar		STENO_HTML_MAIN_HEADER						nil	"description"	)
	(defvar		STENO_HTML_MAIN_ITEM_P0						nil	"description"	)
	(defvar		STENO_HTML_MAIN_ITEM_P1						nil	"description"	)
	(defvar		STENO_HTML_MAIN_ITEM_P2						nil	"description"	)
	(defvar		STENO_HTML_MAIN_ITEM_P3						nil	"description"	)
	(defvar		STENO_HTML_MAIN_ITEM_P4						nil	"description"	)
	(defvar		TEMP								nil	"description"	)
	(defvar		TEMPSTATDESCRIPTION						nil	"description"	)
	(defvar		TOLIST								nil	"description"	)
	(defvar		TSTEST								nil	"description"	)
	(defvar		WITH_CMD_FILE							nil	"description"	)
	(defvar 	*HPS_OUTPUT_MAJOR_TICK* 					nil	"description" )
	(defvar 	*HPS_SEGMENT_SPAN_IDENTIFIER_TS* 				nil	"description" )
	(defvar 	*GNU_GNUWGET_PATH* 						nil	"description" )
	(defvar 	*HPS_ATS_DM_LAMBDA_CONSTRAINT* 					nil	"description" )
	(defvar 	*HPS_PERF_Z_MEANS_I* 						nil	"description" )
	(defvar 	*STENO_INPUTTEXT* 						nil	"description" )
	(defvar 	*STENO_HPS_MAPPED_TUPLESET* 					nil	"description" )
	(defvar 	*HPS_STENO_GNUPLOT_FIGFILE* 					nil	"description" )
	(defvar 	HPS_DNA_HTML_MAIN_ITEM_P0 					nil	"description" )
	(defvar 	BESTVAL 							nil	"description" )
	(defvar 	HPS_COMPARATOR_VALUE  						nil 	"description" )
	(defvar 	HPS_DNA_ITER_XYZ  						nil 	"description" )
	(defvar 	HPS_1DNA_MAGNIFIED_CODED_COMPARISON  				nil 	"description" )
	(defvar 	HPS_1DNA_MAGNIFIED_COMPARISON_DIFFERENCES  			nil 	"description" )
	(defvar 	HPS_1DNA_COMPARATOR_VALUE  					nil 	"description" )
	(defvar 	HPS_COMPARATOR_SIGMA_LEVELS  					nil	"description" )
	(defvar 	HPS_COMPARATOR_THRESHOLD_MEAN  					nil	"description" )
	(defvar 	HPS_COMPARATOR_THRESHOLD_SIGMA  				nil	"description" )
	(defvar 	HPS_MATCHED_COMPARISON_TOTALS  					nil	"description" )
	(defvar 	HPS_MATCHED_COMPARISON_TOTALS_WO  				nil 	"description" )
	(defvar 	HPS_MCT_WO_MEAN  						nil	"description" )
	(defvar 	HPS_MCT_WO_SIGMA  						nil 	"description" )
	(defvar 	HPS_COMPARATOR_THRESHOLD  					nil	"description" )
	(defvar 	HPS_COMPARATOR_OUTLIERS_THRESHOLD  				nil 	"description" )
	(defvar 	HPS_DNA_ALIGNMENT_DATASET  					nil	"description" )
	(defvar 	*HPS_DNA_BESTMATCHES_COARSEGRAIN* 				nil	"description" )
	(defvar 	*HPS_DNA_BESTMATCHES_FINEGRAINED* 				nil	"description" )
	(defvar 	HPS_ALIGNMENT_DATASET 						nil	"description" )
	(defvar 	HPS_DNA_MAGNIFIED_CODED_COMPARISON 				nil	"description" )
	(defvar 	HPS_DNA_COMPARISON_RATING 					nil	"description" )
	(defvar 	HPS_DNA_COMPARISON_RATING_TUPLE 				nil	"description" )
	(defvar 	HPS_DNA_COMPARATOR_TABLE 					nil	"description" )
	(defvar 	*HPS_DNA_COMPARISON_THRESHOLD* 					nil	"description" )
	(defvar 	HPS_DNA_BESTMATCHES_FINEGRAINED 				nil	"description" )
	(defvar 	HPS_FAR_FROM_START						nil	"description" )
	(defvar 	HPS_1DNA_COMPARISON_VECTOR					nil	"description" )
	(defvar 	HPS_DNA_MISMATCH_TOLERANCE_PERCENTAGE				nil	"description" )
	(defvar 	DNA_MAGNIFY_CODE_A						nil	"description" )
	(defvar 	DNA_MAGNIFY_CODE_C						nil	"description" )
	(defvar 	DNA_MAGNIFY_CODE_G						nil	"description" )
	(defvar 	DNA_MAGNIFY_CODE_T						nil	"description" )
	(defvar 	HPS_DNA_NUMBER_RETRY_LABELS					nil	"description" )
	(defvar 	*HPS_1DNA_testsequence_series_filename*				nil	"description" )
	(defvar 	*HPS_1DNA_testsequence_series_headername*			nil	"description" )
	(defvar 	*HPS_1DNA_signature_series_filename*				nil	"description" )
	(defvar 	*HPS_1DNA_signature_series_headername*				nil	"description" )
	(defvar 	*HPS_DNA_comparison_threshold_old* 				nil	"description" )
	(defvar 	*HPS_DNA_comparison_threshold_new* 				nil	"description" )
	(defvar		*HPS_DNA_bestmatches_finegrained_xyz*				nil	"description" )
	(defvar		*HPS_DNA_BEST_MATCHING_PATTERNS_SORTED_BY_RANK_OLD*		nil	"description" )
	(defvar		HPS_DNA_ITERATION_SKIP 						nil	"description" )
	(defvar		HPS_DNA_ITERATION_TEMP 						nil	"description" )
	(defvar		HPS_NUMSEGS_TEMP						nil	"description" )
	(defvar		OLD_START 							nil	"description" )
	(defvar		OLD_END 							nil	"description" )
	(defvar		NEW_START 							nil	"description" )
	(defvar		NEW_END 							nil	"description" )
	(defvar		HPS_DNA_SIMILAR_PATTERN_FLAG 					nil	"description" )
	(defvar		*HPS_DNA_BESTMATCHES_FINEGRAINED_WITH_DUPLICATES* 		nil	"description" )
	(defvar 	*HPS_DNA_BESTMATCHES_COARSEGRAIN_WITH_DUPLICATES* 		nil 	"description" )
	(defvar 	HPS_NEWSTRING 							nil 	"description" )
	(defvar 	*HPS_FILETITLE* 						nil 	"description" )
	(defvar 	HPS_1DNA_MAGNIFIED_COMPARISON_SAMPLING_POINTS 			nil 	"description" )
	(defvar 	NEW_RATING 							nil 	"description" )
	(defvar 	OLD_RATING							nil 	"description" )
	(defvar		*HPS_DNA_DELETION_TRIGGER* 					nil	"description" )
	(defvar		*HPS_DNA_MAX_RESYNCS_LIMIT* 					nil	"description" )
	(defvar		*HPS_DNA_NUM_PAIREDBASES_REQD* 					nil	"description" )
	(defvar		*HPS_DNA_MAXIMUM_START_OFFSET* 					nil	"description" )
	(defvar		HPS_TOTAL_MATCH_COUNT 						nil	"description" )
	(defvar		HPS_LOCAL_MISMATCH_COUNT 					nil	"description" )
	(defvar		HPS_TOTAL_MISMATCH_COUNT 					nil	"description" )
	(defvar		HPS_SIGNATURE_SUBSEQ_TEMP 					nil	"description" )
	(defvar		HPS_SIGNATURE_LOCAL 						nil	"description" )
	(defvar		HPS_TESTSEQ_LOCAL 						nil	"description" )
	(defvar		HPS_TESTSEQ_LOCAL_BASE 						nil	"description" )
	(defvar		HPS_SIGNATURE_LOCAL_BASE 					nil	"description" )
	(defvar		HPS_DNA_NUM_RESYNCS 						nil	"description" )
	(defvar		HPS_POSITION_INDEX_IN_SIGNATURE 				nil	"description" )
	(defvar		HPS_POSITION_WITHIN_TESTSEQ_SUBSEQ 				nil	"description" )
	(defvar		HPS_INTRA_ALIGNMENT_INDEX 					nil	"description" )
	(defvar		*HPS_DNA_HIGHBASE_COUNT_DIFF* 					nil	"description" )
	(defvar		HPS_TESTSEQUE_SUBSEQ_TEMP					nil	"description" )
	(defvar		HPS_COMPARISON_SEQUENCE_RESET 					nil	"description" )
	(defvar		HPS_UNMATCH_REMAINDER_SEQ 					nil	"description" )
	(defvar		*HPS_DNA_FINAL_ALIGNMENT_DATASET* 				nil	"description" )
	(defvar		DNA_COMPARISON_TUPLE_IN_USE 					nil	"description" )
	(defvar		HPS_NUM_BASES_TO_SKIP 						nil	"description" )
	(defvar		HPS_INTRA_ALIGNMENT_INDEX_LOCAL 				nil	"description" )
	(defvar		HPS_ALIGNMENT_SUCCESS 						nil	"description" )
	(defvar		HPS_TABLE_PRINT_FORMAT 						nil	"description" )
	(defvar		*HPS_DNA_INTERNAL_DESCRIPTION_INPUTS* 				nil	"description" )
	(defvar		HPS_DNA_MATCH_RATING_XYZ 					nil	"description" )
	(defvar		HPS_MATCHING_SEQUENCE_TEMP_XYZ 					nil	"description" )
	(defvar		HPS_DNA_MATCH_ALIGNMENT_INDEX_XYZ 				nil	"description" )
	(defvar		PATNUM_LOCAL 							nil	"description" )
	(defvar		HPS_ALIGNMENT_DATASET_LOCAL 					nil	"description" )
	(defvar		HPS_ALIGNMENT_INDEX_LOCAL 					nil	"description" )
	(defvar 	HPS_DNA_MAXIMUM_DISPLACENT_FROM_START				nil 	"description" )
	(defvar		HPS_PS_SLOW_SUM 						nil	"description" )
	(defvar		HPS_PS_FAST_SUM 						nil	"description" )
	(defvar		HPS_PS_FORE_SUM 						nil	"description" )
	(defvar		HPS_PS_SLOW_MEAN 						nil	"description" )
	(defvar		HPS_PS_FAST_MEAN 						nil	"description" )
	(defvar		HPS_PS_FORE_MEAN 						nil	"description" )
	(defvar		HPS_PS_SLOW_SSOE 						nil	"description" )
	(defvar		HPS_PS_FAST_SSOE 						nil	"description" )
	(defvar		HPS_PS_FORE_SSOE 						nil	"description" )
	(defvar		HPS_PS_SLOW_STDV 						nil	"description" )
	(defvar		HPS_PS_FAST_STDV 						nil	"description" )
	(defvar		HPS_PS_FORE_STDV 						nil	"description" )
	(defvar		HPS_PS_SLOW_VAR 						nil	"description" )
	(defvar		HPS_PS_FAST_VAR 						nil	"description" )
	(defvar		HPS_PS_FORE_VAR 						nil	"description" )
	(defvar		HPS_PS_SLOW_LVAL 						nil	"description" )
	(defvar		HPS_PS_FAST_LVAL 						nil	"description" )
	(defvar		HPS_PS_FORE_LVAL 						nil	"description" )
	(defvar		*WIN_OUTPUT_PATH* 						nil	"description" )
	(defvar		*WIN_OUTPUT_PATH_FULL* 						nil	"description" )
	(defvar		*WITH_CMD_FILE* 						nil	"description" )
	(defvar		COMMAND 							nil	"description" )
	(defvar		BASEDIR 							nil	"description" )
	(defvar		*REN_WIN_OUTPUT_PATH* 						nil	"description" )
	(defvar		*HPS_OUTPUTDIR* 						nil	"description" )
	(defvar		*HPS_BASEDIR* 							nil	"description" )
	(defvar		*HPS_HISTOGRAM_HEADER* 						nil	"description" )
	(defvar		*HPS_MSE_POOLED_STD_STACK_LEN* 					nil	"description" )
	(defvar		*HPS_MSE_BOUND_1_WINDOW_LASTVAL* 				nil	"description" )
	(defvar		*HPS_MSE_BOUND_0_WINDOW_LASTVAL* 				nil	"description" )
	(defvar		*HPS_SSE_FORM_STACK_LEN* 					nil	"description" )
	(defvar		*HPS_SSE_WINDOW_LASTVAL* 					nil	"description" )
	(defvar		*HPS_M_PLUS_MP* 						nil	"description" )
	(defvar		LAST_PLOT_X2 							nil	"description" )
	(defvar		LAST_PLOT_X1 							nil	"description" )
	(defvar		HPS_DNA_RESYNC_RESTART_OFFSET 					nil	"description" )
	(defvar		*HPS_ALIGNMENT_SUCCESS_FLAG* 					nil	"description" )
	(defvar		*HPS_DNA_PATTERN_ALIGNMENT_VECTOR* 				nil	"description" )
	(defvar		HPS_ALIGNMENT_VECTOR 						nil	"description" )
	(defvar		*HPS_UNIV_TIME_STACK* 						nil	"description" )
	(defvar		*HPS_DNA_FINDINGS* 						nil	"description" )
	(defvar		*HPS_ACCESS_LDB_SEQS* 						nil	"description" )
	(defvar		*HPS_DNA_FINDINGS_MADE* 					nil	"description" )
	(defvar		HPS_ARCHIVAL_MODE 						nil	"description" )
	(defvar		HPS_DNA_ECOLI_GENOME 						nil	"description" )
	(defvar		HPS_DNA_ECOLI_PART_1 						nil	"description" )
	(defvar		HPS_POSITION_WITHIN_SIGNATU_SUBSEQ				nil	"description" )
	(defvar		*HPS_HISTOGRAM_DATASET_SORTED_FREQUENCIES* 			nil	"description" )
	(defvar 	HPS_DNA_XY_PLOT_MATRIX_DATA 					nil	"description" )
	(defvar 	HPS_DNA_PHYLO_TREE						nil	"description" )
	(defvar		*HPS_1DNA_TESTSEQUENCE_INPUT_BASES* 				nil	"description" )
	(defvar		*HPS_DNA_SEQUENCE_ANALYZER_REPORT* 				nil	"description" )
	(defvar		*HPS_TRANSFORMED_INPUTSERIES* 					nil 	"description" )
	(defvar		*HPS_DNA_SEQUENCE_ANALYZER_REPORT_SUMMARY* 			nil 	"description" )

	(pprint 'HPS_SYSTEM_RESET_DONE)
;; *******************************************************************************************************





;; *******************************************************************************************************
(defun HPS_DNA_GLOBAL_RESET ()
	(HPS_wipeout		*HPS_1DNA_ACTUAL_INPUT_BASES*							)
	(HPS_wipeout		*HPS_1DNA_ACTUAL_INPUT_DATASET*							)
	(HPS_wipeout		*HPS_1DNA_BASES_ONLY*								)
	(HPS_wipeout		*HPS_1DNA_BASES_XY_TIMESERIES*							)
	(HPS_wipeout		*HPS_1DNA_FILEREADER_BASES_SEQUENCE*						)
	(HPS_wipeout		*HPS_1DNA_FULL_INPUT_SEQUENCE_XYZ*						)
	(HPS_wipeout		*HPS_1DNA_INPUT_BASES_SIGNATURE*						)
	(HPS_wipeout		*HPS_1DNA_INPUT_BASES_TEMP*							)
	(HPS_wipeout		*HPS_1DNA_INPUT_TIMESERIES*							)
	(HPS_wipeout		*HPS_1DNA_INPUT_TIMESERIES_CODED*						)
	(HPS_wipeout		*HPS_1DNA_MATCHING_BASES_COMPARISON_TEMP*					)
	(HPS_wipeout		*HPS_1DNA_MATCHING_CODED_COMPARISON_PRETTY_PRINT*				)
	(HPS_wipeout		*HPS_1DNA_MATCHING_CODED_COMPARISON_PRETTY_PRINT_XYZ*				)
	(HPS_wipeout		*HPS_1DNA_MATCHING_CODED_COMPARISON_TEMP*					)
	(HPS_wipeout 		*HPS_1DNA_TESTSEQUENCE_INPUT_BASES* 						)
	(HPS_wipeout		*HPS_1DNA_SIGNATURE_BASES*							)
	(HPS_wipeout		*HPS_1DNA_SIGNATURE_CODED*							)
	(HPS_wipeout		*HPS_1DNA_SIGNATURE_INPUT_DATASET_XYZ*						)
	(HPS_wipeout		*HPS_1DNA_TESTSEQUENCE_BASES*							)
	(HPS_wipeout		*HPS_1DNA_TESTSEQUENCE_CODED*							)
	(HPS_wipeout		*HPS_1DNA_TESTSEQUENCE_INPUT_DATASET_XYZ*					)
	(HPS_wipeout		*HPS_3DNA_ALL_SIG2SUBSEQ_PAIRINGS*						)
	(HPS_wipeout		*HPS_3DNA_ALLPAIRS_SEARCH_RESULT*						)
	(HPS_wipeout		*HPS_3DNA_ALLPAIRS_WITHIN_WINDOW*						)
	(HPS_wipeout		*HPS_3DNA_BASES_CODED*								)
	(HPS_wipeout		*HPS_3DNA_SIGNATURE_BASES*							)
	(HPS_wipeout		*HPS_3DNA_SIGNATURE_CODED*							)
	(HPS_wipeout		*HPS_3DNA_SIGNATURE_DATASET*							)
	(HPS_wipeout		*HPS_3DNA_SIGNATURE_SEGTABLE*							)
	(HPS_wipeout		*HPS_3DNA_STENO_SEGTABLE*							)
	(HPS_wipeout		*HPS_3DNA_TESTSEQUENCE_BASES*							)
	(HPS_wipeout		*HPS_3DNA_TESTSEQUENCE_CODED*							)
	(HPS_wipeout		*HPS_3DNA_TESTSEQUENCE_DATASET*							)


	(setf		*HPS_1DNA_ACTUAL_INPUT_BASES*					nil		)
	(setf		*HPS_1DNA_ACTUAL_INPUT_DATASET*					nil		)
	(setf		*HPS_1DNA_ALIGNMENT_INDEX_WITHIN_TESTSEQ*			nil		)
	(setf		*HPS_1DNA_BASES_ONLY*						nil		)
	(setf		*HPS_1DNA_BASES_XY_TIMESERIES*					nil		)
	(setf		*HPS_1DNA_ENCODED_SEQUENCE_FILE*				nil		)
	(setf		*HPS_1DNA_ENDPOINT_SIGNATURE_END*				nil		)
	(setf		*HPS_1DNA_ENDPOINT_SIGNATURE_START*				nil		)
	(setf		*HPS_1DNA_FILEREADER_BASES_SEQUENCE*				nil		)
	(setf		*HPS_1DNA_FILLER_BASES_LEN*					nil		)
	(setf		*HPS_1DNA_FULL_INPUT_SEQUENCE_XYZ*				nil		)
	(setf		*HPS_1DNA_INPUT_BASES_SIGNATURE*				nil		)
	(setf		*HPS_1DNA_INPUT_BASES_TEMP*					nil		)
	(setf		*HPS_1DNA_INPUT_BASES_TESTSUBSEQ*				nil		)
	(setf		*HPS_1DNA_INPUT_TIMESERIES*					nil		)
	(setf		*HPS_1DNA_INPUT_TIMESERIES_CODED*				nil		)
	(setf		*HPS_1DNA_MATCHING_BASES_COMPARISON_TEMP*			nil		)
	(setf		*HPS_1DNA_MATCHING_CODED_COMPARISON_PRETTY_PRINT*		nil		)
	(setf		*HPS_1DNA_MATCHING_CODED_COMPARISON_PRETTY_PRINT_XYZ*		nil		)
	(setf		*HPS_1DNA_MATCHING_CODED_COMPARISON_TEMP*			nil		)
	(setf		*HPS_1DNA_MUTATED_BASES*					nil		)
	(setf		*HPS_1DNA_MUTATED_SEQUENCE*					nil		)
	(setf		*HPS_1DNA_SEQUENCE_FILENAME*					nil		)
	(setf		*HPS_1DNA_SERIES_STABILIZER_FILLER*				nil		)
	(setf		*HPS_1DNA_SERIES_TITLE*						nil		)
	(setf		*HPS_1DNA_SIGNATURE_BASES*					nil		)
	(setf		*HPS_1DNA_SIGNATURE_BASES_LEN*					nil		)
	(setf		*HPS_1DNA_SIGNATURE_CODED*					nil		)
	(setf		*HPS_1DNA_SIGNATURE_INPUT_DATASET_XYZ*				nil		)
	(setf		*HPS_1DNA_TESTSEQUENCE_BASES*					nil		)
	(setf		*HPS_1DNA_TESTSEQUENCE_CODED*					nil		)
	(setf		*HPS_1DNA_TESTSEQUENCE_INPUT_DATASET_XYZ*			nil		)
	(setf		*HPS_3DNA*							nil		)
	(setf		*HPS_3DNA_ALL_SIG2SUBSEQ_PAIRINGS*				nil		)
	(setf		*HPS_3DNA_ALLPAIRS_SEARCH_RESULT*				nil		)
	(setf		*HPS_3DNA_ALLPAIRS_WITHIN_WINDOW*				nil		)
	(setf		*HPS_3DNA_BASES_CODED*						nil		)
	(setf		*HPS_3DNA_DIFF_DUR*						nil		)
	(setf		*HPS_3DNA_DIFF_IDX*						nil		)
	(setf		*HPS_3DNA_DIFF_VAL*						nil		)
	(setf		*HPS_3DNA_ENCODED_SEQ_FILE*					nil		)
	(setf		*HPS_3DNA_ENDPOINT_SIGNATURE_END*				nil		)
	(setf		*HPS_3DNA_ENDPOINT_SIGNATURE_START*				nil		)
	(setf		*HPS_3DNA_ENDPOINT_TESTSEQUENCE_END*				nil		)
	(setf		*HPS_3DNA_ENDPOINT_TESTSEQUENCE_START*				nil		)
	(setf		*HPS_3DNA_ENDPOINTS_SIGNATURE*					nil		)
	(setf		*HPS_3DNA_ENDPOINTS_TESTSEQUENCE*				nil		)
	(setf		*HPS_3DNA_HASH_LOOKUP_KEY*					nil		)
	(setf		*HPS_3DNA_HASH_LOOKUP_VAL*					nil		)
	(setf		*HPS_3DNA_INPUTFILE*						nil		)
	(setf		*HPS_3DNA_SEGTABLE_FILE*					nil		)
	(setf		*HPS_3DNA_SEGTABLE_HASHTABLE*					nil		)
	(setf		*HPS_3DNA_SIGNATURE_BASES*					nil		)
	(setf		*HPS_3DNA_SIGNATURE_CODED*					nil		)
	(setf		*HPS_3DNA_SIGNATURE_DATASET*					nil		)
	(setf		*HPS_3DNA_SIGNATURE_SEGTABLE*					nil		)
	(setf		*HPS_3DNA_SIGNATURE_SIZE*					nil		)
	(setf		*HPS_3DNA_STENO_SEGTABLE*					nil		)
	(setf		*HPS_3DNA_TESTSEQUENCE_BASES*					nil		)
	(setf		*HPS_3DNA_TESTSEQUENCE_CODED*					nil		)
	(setf		*HPS_3DNA_TESTSEQUENCE_DATASET*					nil		)
	(setf		*HPS_3DNA_TESTSEQUENCE_SIZE*					nil		))
;; *******************************************************************************************************




